### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by bebraw** [AdeleD/react-paginate#1]
Take a look at https://www.npmjs.com/package/react-pagination . I had a conversation with the NPM folks. Apparently the package was released using a very old and buggy version of NPM. Could you please republish it using a new version to make the package available?

**Comment by AdeleD** [comment]
The package has been renamed "react-paginate". It is available here : https://www.npmjs.com/package/react-paginate

**Comment by bebraw** [comment]
Ok, cool.
