### ISSUE TITLE
Buttons don't work

### ISSUE THREAD

**Issue by Rubenvdveen** [AdeleD/react-paginate#100]
Previous button seems to be disabled, also number 1 is always disabled.
Next button will always redirect to page 2.
The break-line dots dont change. For example, if i have 100 pages, it shows 1-4...96-100. but if i navigate to page 4, the dots stay at the same place, and i can never get to page 5-95. Only if i would show all pages, but thats just not an option.

`          

    handlePageClick = (data) => {

      let selected = data.selected;
      console.log('page clicked')
      console.log(selected)
      let offset = Math.ceil(selected * c.itemsPerPage);

      this.setState({
        offset: offset,
      }, () => {
        this._loadItems();
      });
    };

     this.setState({ loading: true })
       api(apiUrl).then(response => {

         const items = response.data.map(({ id, name, number_children }) => ({ id, label: name, numberChildren:number_children }))
         this.setState({
           items,
           loading: false,
           pageNum: Math.ceil(response.pagination.total / c.itemsPerPage)
          })
       })
     }

           <ReactPaginate
                   previousLabel={"previous"}
                   nextLabel={"next"}
                   breakLabel={<a href="">...</a>}
                   breakClassName={"break-me"}
                   pageNum={this.state.pageNum}
                   marginPagesDisplayed={2}
                   pageRangeDisplayed={5}
                   clickCallback={this.handlePageClick}
                   containerClassName={"pagination"}
                   subContainerClassName={"pages pagination"}
                   activeClassName={"active"} />
`

**Comment by jonas-db** [comment]
@Rubenvdveen i have the same problem, how have you solved it?

**Comment by lorenamelor** [comment]
use of `forcePage` with the current page. So everything works well.

**Comment by lorenamelor** [comment]
Use `forcePage` with the current page. So everything works well.
