### ISSUE TITLE
Links without a href don't get a cursor:pointer and are inaccessible

### ISSUE THREAD

**Issue by hkrutzer** [AdeleD/react-paginate#102]
In https://github.com/AdeleD/react-paginate/commit/e5f92d213aa204a8825484bd735878a7f222656c hrefs were removed, which means they are no longer accessible, and don't get a pointer as cursor when hovered. I don't think the change above was the correct way of fixing the issue.

Willing to submit a PR.

**Comment by Rubenvdveen** [comment]
+1.
Anyway, you can just fix that in your css ofcourse, but that would make your code kind of dirty.

**Comment by hkrutzer** [comment]
You can, but a `<a>` without a href cannot be tabbed through either.

**Comment by hozefaj** [comment]
@hkrutzer I think https://github.com/AdeleD/react-paginate/pull/108 fixes tabbbing issue.
