### ISSUE TITLE
How-to Apply Custom-Styles?

### ISSUE THREAD

**Issue by e-karma** [AdeleD/react-paginate#103]
Thanks for creating this!

Is there any best way to use with JSS? or should I apply styles in a separate style sheet?  Thanks in advance

**Comment by coljung** [comment]
im using react-toolbox which in turn uses css-modules.
i find it easier to have separate style sheets which i import when i need.

**Comment by Rubenvdveen** [comment]
You can just go into your main css, and give the pagination some classnames.
