### ISSUE TITLE
Pagination generated as of 2nd <li> on created list

### ISSUE THREAD

**Issue by coljung** [AdeleD/react-paginate#104]
For some reason I can't yet fully understand, my pagination is loading like this:

``` javascript

<li><a>1</a></li>    // links to page 0 ( which doesnt exist  )
<li class="active"><a>2</a></li> //links to page 1
<li><a>3</a></li> //links to page 2
<li><a>4</a></li> //links to page 3 , also no link for page 4
<li class="next"><a>next</a></li>

```

Any ideas what i might be doing wrong ? My ReactPaginate component looks like this:

```javascript
<ReactPaginate
                   previousLabel={"previous"}
                   nextLabel={"next"}
                   breakLabel={<a href="">...</a>}
                   breakClassName={"break-me"}
                   pageNum={this.state.pageNum}
                   marginPagesDisplayed={2}
                   pageRangeDisplayed={3}
                   clickCallback={this.handlePageClick.bind(this)}
                   containerClassName={'pagination'}
                   subContainerClassName={"pages pagination"}
                   activeClassName={'active'} />
```

**Comment by Rubenvdveen** [comment]
Had the same problem for some time. After some time, i just created my own pagination component. 
I think the way to fix it, is to go into node modules>React Paginate, and go to PaginationBoxView.js.
This pagination component will start everything with the number 1. Altough, my own pagination would only work if i started it with the number 0. I guess that's the problem.

**Comment by coljung** [comment]
It actually had nothing to do with my implementation.

I did some tests and found that when replicating the react-paginate demo with my data, i would have the same problem, which pointed me to an api problem instead.

So, all in all the problem was coming from somewhere else and has been fixed now.
