### ISSUE TITLE
Using react-paginate with a table

### ISSUE THREAD

**Issue by jinxac** [AdeleD/react-paginate#105]
I am using table in which i have 10 rows. Above my table I have few filters and a search bar. I am doing server side filtering and search. 

I am using redux store to update the table entities based on API results. Now say I have 40 results, I will have 4 pages. All this works fine. Now in a scenario where using react paginate I move to page 2 of the table and  now I try searching/filtering. The results are updated in the table but the react-paginate still shows 2nd page as selected page. 

Is there any way it can be moved to first page when I search/filter?Can you please me on this?

**Comment by rouzazari** [comment]
@jinxac, I had a similar problem with my app, which uses redux store as well. 

Not sure if this is a hack or a good use: I use the ``forceSelected`` attribute of the ``ReactPaginate`` element to update the page number when filtering. This might work for you.

**Comment by jinxac** [comment]
I think its not actually a hack, even i had the same thing in mind.

So I was assuming you set the value of ```forceSelected``` in ```store``` set to ```null``` and whenever filtering occurs you set to 1 and when filtering is clearing is cleared again to ```null```?
