### ISSUE TITLE
problem with module-resolution using type script

### ISSUE THREAD

**Issue by mulmulovich** [AdeleD/react-paginate#106]
getting ` [ts] Cannot find module 'react-paginate'.`
when trying to `import ReactPaginate from 'react-paginate'`
please suggest proper configuration in order to be able to import the component

**my tsconfig.json:**
`{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "jsx": "react",
        "noEmit": true,
        "types": [
            "node",
            "mocha",
            "sinon",
            "core-js"
        ]
    },
    "exclude": []
}`
let me know if more details are needed

**Comment by San4oPanso** [comment]
@mulmulovich Had same problem. Solution is ` "allowJs": true `, in tsconfig.json
Any updates from your side?

**Comment by dcoleman007** [comment]
having problems with typescript too.  I tried `allowJS:true` with no success

**Comment by AdeleD** [comment]
Please re-open the issue if necessary.
