### ISSUE TITLE
The description is wrong

### ISSUE THREAD

**Issue by finom** [AdeleD/react-paginate#109]
Please push changes (at least README) to master at the same time when you publish a release on NPM. I was trying to figure out why ``pageCount`` and ``onPageChange`` don't work but there was just a difference between the description on Github and actual version of the component. Please respect the community.

**Comment by finom** [comment]
Also I would recommend you to use semantic-release to keep everything always up to date.

**Comment by AdeleD** [comment]
Done. Sorry for the delay before the release.
