### ISSUE TITLE
Props description is wrong

### ISSUE THREAD

**Issue by laurentiu1981** [AdeleD/react-paginate#110]
I did not verified all of them but **initialPage** and **forcePage** are clearly wrong. Lookin in code source it seems that we should use: **forceSelected**, **initialSelected**

**Comment by AdeleD** [comment]
These changes appeared just a few minutes ago. Please look at this: https://github.com/AdeleD/react-paginate/blob/master/HISTORY.md.
Use `forceSelected` and `initialSelected` with react-paginate <= 3.0.0.
`initialPage` and `forcePage` with react-paginate == 4.0.0.

Thanks
