### ISSUE TITLE
how to use a clickCallback

### ISSUE THREAD

**Issue by yourenA** [AdeleD/react-paginate#111]
I want to ask a question . when I click the paginate`s button,I want to judge  the paginate could jump to another page or not.
Like that I was on the first page , I click th second page button , when the conditions satisfaction , I could  jump to second page . when the condition is not satisfied , I still on the first page.

**Comment by hozefaj** [comment]
`clickCallback` (actually `onPageChange`) is accepts a function where it receives an argument of the selected page. You can use the function test for your use case.

Example:
```
<ReactPaginate 
  onPageChange={({ selected }) => {
    this.props.updateSelectedPage(selected);
  }}
>
```
