### ISSUE TITLE
Previous and Next Arrow Custom Styling Issue

### ISSUE THREAD

**Issue by sayayinR** [AdeleD/react-paginate#112]
Hi,
I need to use bootstrap glyphicon classes for the arrows. 

I specified space for props and specified classes for the arrows

```
  previousLabel={' '}
  nextLabel = {' '}
  previousClassName = {'glyphicon glyphicon-menu-left'}
  nextClassName = {'glyphicon glyphicon-menu-right'}
```

Styles look fine but I cannot click on the arrows, as soon as I add text instead of space it works. I also added text and tried if I could do:
```

display: inline-block;
text-indent: -9999px;
```

But it does not work. I'm sure there has to be a way to style arrows without any text?

**Comment by sayayinR** [comment]
Guess I solved the issue by adding:

`opactity: 0;`

But still wondering if there are any other options.

**Comment by AdeleD** [comment]
There are probably various ways to do that, but another one is to set property `display: block;` on <a> tags.
