### ISSUE TITLE
Separating the different "Breaks"

### ISSUE THREAD

**Issue by ssolders** [AdeleD/react-paginate#115]
In the case of having a large number of pages, say a 100. If you go to page 50, you will get 2 instances "breaks", one on the left, one of the right. In this example I want to display my breaks as ellipsis (...). 

<img width="459" alt="screen shot 2016-12-19 at 15 39 03" src="https://cloud.githubusercontent.com/assets/7665542/21316500/51efb00e-c601-11e6-8ad2-ea4a333dda9b.png">

In my world, the feature should allow the user to step multiple pages forward/backward, helping the user to speed up navigation in the pagination. 

As far as I can see there is no way to separate these two "breaks". Is this by design or have I missed something?

I want to be able to step back multiple pages if the user clicks the left one, and in the case of clicking the right one I would like to step multiple pages forward.

**Comment by ssolders** [comment]
Okay, so we worked out a solution for this, it's not ideal but it works.

```
_onEllipsisTouchTap(e, selectedPage) {
    const breakButtons = this.refs.pagination.getElementsByClassName('break-button'),
    elementArray = Array.prototype.slice.call(breakButtons),
    index = elementArray.indexOf(e.target);

    if (index === 0) {
        alert("tapped left");
    } else if (index === 1) {
        alert("tapped right");
    }
}

render () {
    return (
        <div ref="pagination" id="react-paginate" className="dynamic-pagination-container">
            <Pagination {...props}  
                breakLabel={
                <span className="break-button" 
                onTouchTap={this._onEllipsisTouchTap.bind(this)}>...</span>}
        </div>
    );
}
```

**Comment by treyhuffine** [comment]
Thanks for the solution @ssolders. It would be great to something in master that addresses thig.

**Comment by kstratis** [comment]
@ssolders solution didn't work for me. Here's my take on it (with a bit of help from jquery/zepto):

```js
determineDirection (element) {
    // Get the actual li element containing the ellipsis span
    let ellipsisDomElement = $(element).parent(); 
    let direction = '+';
    /* If the active page is on our right that means that by 
        pressing the ellipsis button we should move to the left. 
        In other words we should flip back. Otherwise we  
        flip forward. */
    ellipsisDomElement.nextAll().each((i, element)=>{
      if ($(element).hasClass('active')){
        direction = '-';
        return false;  // break from the $.each loop
      }
    });
    return direction;
  };
```

I am using it like this:

```js
const sign = this.determineDirection(e.target);
if (sign === '+') {
  this.handlePageClick(this.state.selectedPage + 2, true);
} else{
  this.handlePageClick(this.state.selectedPage - 2, true);
}
```

Hope this helps someone in the future.

**Comment by AdeleD** [comment]
I'm closing the issue as the feature has been implemented.
