### ISSUE TITLE
Error: Cannot find module 'react-addons-create-fragment'

### ISSUE THREAD

**Issue by liesislukas** [AdeleD/react-paginate#117]
add it to your dependencies, fixed after `npm i --save react-addons-create-fragment `

**Comment by mdboop** [comment]
@liesislukas you should just add `react-addons-create-fragment` as a dependency to your project. Should work just fine.

**Comment by liesislukas** [comment]
yes, that's what i've did. Had some typo in 1st post, updated npm command. Also added it to this repo for future users, you can see open pull request
