### ISSUE TITLE
Make pagination button highlight area clickable

### ISSUE THREAD

**Issue by bikunem** [AdeleD/react-paginate#125]
Users are expecting to be able to click the highlighted background of the page buttons. But only the actual page number hyperlink is clickable.

This would also help increase the hit area for range of motion impaired users.

We will take a look to see if we can fix this with a PR.

**Comment by AdeleD** [comment]
We can't do this for accessibility reasons. See: https://github.com/AdeleD/react-paginate/issues/89 and https://github.com/AdeleD/react-paginate/pull/108.
If you want to make all page buttons clickable you can use CSS attributes (`display: block` on `<a>` tags).

**Comment by jraut** [comment]
There is also the `pageLinkClassName` which can be used instead of directly styling `<a>`

**Comment by bikunem** [comment]
Yes, we were able to figure this out via our local css.  Thank you for the help.
