### ISSUE TITLE
Cannot resolve module 'react-addons-create-fragment'

### ISSUE THREAD

**Issue by oscarsmartwave** [AdeleD/react-paginate#127]
Building react-paginate v4.0.0 with webpack v1.14.0 gets me this Error:

ERROR in ./~/react-paginate/dist/PaginationBoxView.js
Module not found: Error: Cannot resolve module 'react-addons-create-fragment' in ./node_modules/react-paginate/dist
@ ./~/react-paginate/dist/PaginationBoxView.js 17:33-72

**Comment by mlukaszczyk** [comment]
Quickfix
run: `npm install --save react-addons-create-fragment`

**Comment by ilyakatz** [comment]
Doesn't this mean that `react-addons-create-fragment` needs to be a dependency of this module?

**Comment by weslleyaraujo** [comment]
also faced this issue ✋

quickfix mentioned by @mlukaszczyk works 😀
