### ISSUE TITLE
hide pagination based on page count

### ISSUE THREAD

**Issue by hozefaj** [AdeleD/react-paginate#132]
Is there a config or some other way that `react-paginate` will not get added to DOM when the `pageCount` changes such that it no longer warrants pagination.

right now i am doing this via using `if` condition, but was wondering whether there was a way to do this through some callback supported by `react-paginate` itself?

**Comment by AdeleD** [comment]
No there isn't, the `pageCount` attribute you set when initializing the component is used as is; without any callback called before.

**Comment by gabma** [comment]
Why not juste define your className like this with this.state.pageCount as parameter
`
containerClassName={"pagination page-"+this.state.pageCount} 
`
and then play with CSS display

**Comment by hozefaj** [comment]
Yes, there are multiple ways to solve this. I figured rather than everyone doing its own implementation, it something the component can support.

Closing the issue.

**Comment by sebmor** [comment]
It could definitely be a nice improvement to have it not render by default is pagecount is only 1

**Comment by hozefaj** [comment]
We can use `pageCount` prop to return null if there its value is 0. @AdeleD How does this proposal sound?
