### ISSUE TITLE
React warning about numeric keys

### ISSUE THREAD

**Issue by g-p-g** [AdeleD/react-paginate#14]
When rendering this component, React gives the following warning:

----

Warning: Child objects should have non-numeric keys so ordering is preserved. Check the render method of PaginationListView. See https://fb.me/react-warning-keys for more information.

----

**Comment by scottzer0** [comment]
same.  let's fix this.  it'd like to use this instead of writing my own.  the fix is pretty easy.

**Comment by AdeleD** [comment]
I have already added the React.addons.createFragment here: https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationListView.js#L83. So I don't understand why React still display this warning message for the moment. But if you have an idea to fix the problem please tell me how or feel free to make a pull request.

**Comment by g-p-g** [comment]
Hi, sure. The issue is that in PaginationListView you're doing `items[String(index)]` which defines all keys as numbers disguised as strings. That's what React is complaining about. If you do a trivial change to `items['x' + String(index)]` you will notice the warning disappears.

**Comment by AdeleD** [comment]
Oh ok! Thank you very much! I will fix that. I find it weird because my disguised string *is* a string, you don't think so? :)
