### ISSUE TITLE
initialPage breaks marginPagesDisplayed and pageRangeDisplayed on the first render

### ISSUE THREAD

**Issue by akoidan** [AdeleD/react-paginate#143]
```
      <ReactPaginate previousLabel={"❮"}
                     nextLabel={"❯"}
                     breakLabel={<a target="_blank">...</a>}
                     breakClassName={"break-me"}
                     pageCount={this.props.entriesPagesCount}
                     marginPagesDisplayed={2}
                     pageRangeDisplayed={5}
                     initialPage={this.props.currentPage}
                     containerClassName={"pagination"}
                     subContainerClassName={"pages pagination"}
                     activeClassName={"active"} />
```

1. When `initialPage` type is str it will render as shown on the top screen.
1. When `initialPage` type is number it will render as shown on the bottom screen.

I think component should throw an error in case it doesn't support strings and doesn't display at all. Or it should render without issues if it doesn't. In other cases it could cost some time for developers when component "seems" to work.

![image](https://cloud.githubusercontent.com/assets/1336703/24293106/d8a756f6-1098-11e7-9be3-62180a058938.png)

**Comment by AdeleD** [comment]
I think that's the purpose of propTypes: https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L20
