### ISSUE TITLE
Active page not working

### ISSUE THREAD

**Issue by guilherme6191** [AdeleD/react-paginate#144]
Hey guys, good work.

I followed the demo and it all works fine except for the active page CSS. Just the first one is blue/active and when I change the page it doesn't activate the current one.

I realized that happens because the component is being refreshed so it as default it gets the first page as current.
If I'm correct, I'd like to suggest maybe add a new `prop` to tell the react-paginate which is the current page.

Just to be clear, I refresh the component every page change because I make a new request to get that specific chunk of data so I won't have to load a huge amount of data at once.

**Comment by mundosk8** [comment]
You can disable that, by setting the prop disableInitialCallback to false

**Comment by guilherme6191** [comment]
Thanks for the quick answer.

Still doesn't work for me. Maybe it's because my component that contains the react-paginate is being also refreshed. Do you think that could happen?

```
<ReactPaginate
        previousLabel={'previous'}
        nextLabel={'next'}
        breakLabel={<a href="">...</a>}
        breakClassName={'break-me'}
        pageCount={pageCount}
        marginPagesDisplayed={2}
        pageRangeDisplayed={7}
        onPageChange={handlePageClick}
        containerClassName={'pagination'}
        subContainerClassName={'pages pagination'}
        activeClassName={'active'}
        disableInitialCallback={false}
      />
```

**Comment by mundosk8** [comment]
I didn't understand your question. Maybe now its related to your component and not with the react-paginate.

**Comment by guilherme6191** [comment]
Yeah, probably because my component is being refreshed. I'll check it out.

Thanks!
