### ISSUE TITLE
having an issue using this with typescript

### ISSUE THREAD

**Issue by davidcoleman007** [AdeleD/react-paginate#145]
I'm new to typescript, and I'm hoping someone can help.  I'm trying to use this component in a typescript react app.

I import as so:
```javascript
import ReactPaginate from 'react-paginate';
```

when using the exact code from the example in the demos folder, I get this in my console:
![image](https://cloud.githubusercontent.com/assets/41075/24335552/7c08002e-1234-11e7-848e-b3db1079b8b4.png)
![image](https://cloud.githubusercontent.com/assets/41075/24335557/8eb5ed6c-1234-11e7-9658-e90b3ad1be89.png)
![image](https://cloud.githubusercontent.com/assets/41075/24335565/9e520dbe-1234-11e7-8ec5-f5752d1d6fc3.png)

the component is defined in my tsx as so:
```jsx
                <ReactPaginate previousLabel={"previous"}
                       nextLabel={"next"}
                       breakLabel={<a href="">...</a>}
                       breakClassName={"break-me"}
                       pageCount={12}
                       marginPagesDisplayed={2}
                       pageRangeDisplayed={5}
                       onPageChange={this.onPageChange.bind(this)}
                       containerClassName={"pagination"}
                       subContainerClassName={"pages pagination"}
                       activeClassName={"active"} 
                       />
```

onPageChange is defined like this:
```js
    onPageChange(data:any) {
        console.log('onPageChange');
    }
```

sometimes if i refresh a few times i get this:
![image](https://cloud.githubusercontent.com/assets/41075/24335583/f65c830e-1234-11e7-8bce-e02bf17384eb.png)

now obviously, the react-paginate props are not part of a "div" and strangely, the error appears to descend from the LinearProgress Material-ui component in the stack trace...  I have added `allowJs:true` to my tsconfig

**Comment by wenduzer** [comment]
import * as ReactPaginate from 'react-paginate'

**Comment by racheliWeiss** [comment]
i  am try to create  paginatem  and this give me error
![image](https://user-images.githubusercontent.com/75696575/120631454-93346d80-c470-11eb-8070-0784cb07d6f8.png)
![image](https://user-images.githubusercontent.com/75696575/120631602-ba8b3a80-c470-11eb-9245-c5527a5ad7c6.png)
![image](https://user-images.githubusercontent.com/75696575/120631669-cd9e0a80-c470-11eb-8a44-32d69605a0f3.png)
