### ISSUE TITLE
No page numbers in demo

### ISSUE THREAD

**Issue by xvonabur** [AdeleD/react-paginate#149]
Hello! I'm having a problem with provided demo. After successful installation and running I do not have page numbers. Only "Next" and "Previous" buttons (screenshot attached). Do I need some additional configuration to see buttons with page numbers?
<img width="258" alt="screen shot 2017-04-08 at 18 50 21" src="https://cloud.githubusercontent.com/assets/616857/24830335/db223cf2-1c8c-11e7-853d-71d27a53dd66.png">

By the way, I'm using Node 7.7.1

**Comment by hozefaj** [comment]
I have been seeing this now. Using version `4.3.1`

**Comment by AdeleD** [comment]
That's strange! I can't reproduce the issue. Are you running the server with the `make serve` command?

**Comment by hozefaj** [comment]
Its been while since I encountered this, but pretty sure I ran `make serve` command.

**Comment by xvonabur** [comment]
Yeap, I was running `make serve` command too. Android 7.1 emulator is the one I tested.
