### ISSUE TITLE
clickCallback not invoked when click on prev or next

### ISSUE THREAD

**Issue by g-p-g** [AdeleD/react-paginate#15]
Hello,

This is a bit strange because I remember seeing this work, but now when I click on next/prev (instead of a specific page number) the clickCallback function is not called.

Taking `handleNextPage` as an example, shouldn't this:

```
if (this.state.selected < this.props.pageNum - 1) {
      this.setState(function (previousState, currentProps) {
        return { selected: previousState.selected + 1 };
      }, (function () {
        this.handlePageSelected(this.state.selected);
      }).bind(this));
    }
```

actually be

```
if (this.state.selected < this.props.pageNum - 1) {
      this.setState(function (previousState, currentProps) {
        return { selected: previousState.selected + 1 };
      }, (function () {
        this.clickCallback();
      }).bind(this));
    }
```

?

That is, after changing the selected page invoke the callback. The issue is that `handlePageSelected` will receive a selected page that is equal to the current one, and won't fire the callback.

**Comment by AdeleD** [comment]
Probably because I merged this pull request: https://github.com/AdeleD/react-paginate/pull/13. I came back to the previous version. This should work better.
