### ISSUE TITLE
start pages amount greater then end pages amount

### ISSUE THREAD

**Issue by jsruvi** [AdeleD/react-paginate#156]
There is an issue. When selected first page - it shows 4 start items and 2 end items http://joxi.ru/gmvzqWvU9VxNma
but when selected last page it shows 2 start items and 3 end items http://joxi.ru/12MlD6YTeYMwmJ

**Comment by AdeleD** [comment]
Did you set a value for the prop `marginPagesDisplayed`? Which version of react-paginate do you use?

**Comment by tilvan** [comment]
@AdeleD had the same issue.
`marginPagesDisplayed = 0, pageRangeDisplayed = 5`
But on the first page I have 6 items
![image](https://user-images.githubusercontent.com/1024347/60723048-43269680-9f3b-11e9-9bfa-22a1b0465b03.png)
