### ISSUE TITLE
The Next <li> is not receiving class disabled

### ISSUE THREAD

**Issue by dlinch** [AdeleD/react-paginate#158]
I am using the disabledClassName prop to set the class name for the disabled previous and next buttons to the class name "disabled". This is the default behavior, but I wanted to be explicit. Currently, it works with the previous button while on page 1, but the next button is not receiving the class name when I am on the last page. 

I gave the disabled class a simple "display: none;" style so that the previous and next buttons would disappear when you are on the first and last pages respectively. I watched the html update using the developer tools, and the disabled class is never assigned to the "Next" li element like it is for "Previous".

I am rendering the pageCount and forcedPage prop on every render, as I have some additional filtering that I use my click handler to mimic rendering page one when an additional filter is applied. I removed these for the sake of testing if these were causing and issue, and it seems unrelated but figured I'd share anyway.

**Comment by kaushal4340** [comment]
@AdeleD ??

**Comment by AdeleD** [comment]
It works for me when I instantiate the component with `disabledClassName={"disabled"}`.
Can you show me the part of your code where you instantiate the `react-paginate` component?

**Comment by kaushal4340** [comment]
After some efforts I figured out issue in my code,
I forgot to use Math.ceil while calculating the pageCount,
After this change this issue is resolved.
@AdeleD Thanks for your attention.

**Comment by dlinch** [comment]
This fixes my issue as well! Thanks @kaushal4340 for figuring that out. I'll close the issue.
