### ISSUE TITLE
No option for jumping to first and last page

### ISSUE THREAD

**Issue by ashishchoudhary12** [AdeleD/react-paginate#159]
what happen if i have 100 pages!!!! how can i jump to last one??

**Comment by bobber205** [comment]
are you not able to click on the last page?

**Comment by ashishchoudhary12** [comment]
if you see there is no option for first and last page

**Comment by bobber205** [comment]
That makes no sense.

**Comment by ashishchoudhary12** [comment]
Suppose I have 100 pages then
how will I go to 100th page directly ???
By pressing next next till 100th?????????
It's rubbish

**Comment by AdeleD** [comment]
Hello @ashishchoudhary12,
To go to the 100th page directly, you can instantiate the component with prop `marginPagesDisplayed`. Try with `marginPagesDisplayed={2}` for instance.
```
<ReactPaginate 
    pageCount={this.state.pageCount}
    marginPagesDisplayed={2}
    pageRangeDisplayed={5}
    onPageChange={this.handlePageClick} />
```
You will obtain something like this:
![react-paginate-margins](https://user-images.githubusercontent.com/942068/27263243-ab756f18-5465-11e7-9f71-21eda81f67ea.png)

It allows you to click on the last page directly.

Hope this helps.

**Comment by ashishchoudhary12** [comment]
thanks Alex Wait

**Comment by daveb0t** [comment]
Sorry for bumping a closed thread but if you have 100 pages and want to quickly get to 50, is there an easy way?
