### ISSUE TITLE
The last page doesn't show break label

### ISSUE THREAD

**Issue by Jwan622** [AdeleD/react-paginate#162]
```
<ReactPaginate
          previousLabel={
            <Caret direction="left" />
          }
          nextLabel={
            <Caret direction="right" />
          }
          pageCount={this.state.pageCount}
          marginPagesDisplayed={0}
          breakLabel={`OF ${this.state.pageCount}`}
          pageRangeDisplayed={0}
          onPageChange={this.handlePageClick}
          containerClassName="pom-Paginate"
          subContainerClassName="pages pagination"
          activeClassName="active"
          nextLinkClassName="nextLink"
          extraAriaContent="0000000000000"
          previousLinkClassName="previousLink"
        />
```

That is my component. My breakLabel doesn't show up when I'm on the last page. How come?

We were trying to do something creative with the `breakLabel` and we set it to `OF ${this.state.pageCount`} so it would read `1 of 5` or `3 of 5` but on the last page it only says `5`. Why is this? We assume some logic is preventing this from happening, but should it? Can this be configurable?

**Comment by qborreda** [comment]
+1 happens to me as well ..

**Comment by MonsieurV** [comment]
Could someone add a Jest test to reproduce the bug?

https://github.com/AdeleD/react-paginate/tree/master/__tests__
