### ISSUE TITLE
PaginationBoxView.js issue only on Internet Explorer

### ISSUE THREAD

**Issue by forgo** [AdeleD/react-paginate#165]
I could use some help to debug an issue which seems to be happening in react-paginate:

I'm running into an error where we only see our client app break in internet explorer.

Normally, I wouldn't bother supporting IE (will this browser ever die?), but our security review team is insisting on it because, ironically, one of their tools needs to run in IE.

Best as I can tell, the first non-React code to show up in my debug call stack comes from the PaginationBoxView.js file:

In here, `_createClass(PaginationBoxView, [ ... ])` has an "render" section which defines the `render()` function which appears to be called before the error is encountered:

```javascript
{
    key: 'render',
    value: function render() {
      var disabled = this.props.disabledClassName;

      var previousClasses = (0, _classnames2.default)(this.props.previousClassName, _defineProperty({}, disabled, this.state.selected === 0));

      var nextClasses = (0, _classnames2.default)(this.props.nextClassName, _defineProperty({}, disabled, this.state.selected === this.props.pageCount - 1));

      return _react2.default.createElement(
        'ul',
        { className: this.props.containerClassName },
        _react2.default.createElement(
          'li',
          { className: previousClasses },
          _react2.default.createElement(
            'a',
            { onClick: this.handlePreviousPage,
              className: this.props.previousLinkClassName,
              href: this.hrefBuilder(this.state.selected - 1),
              tabIndex: '0',
              onKeyPress: this.handlePreviousPage },
            this.props.previousLabel
          )
        ),
        (0, _reactAddonsCreateFragment2.default)(this.pagination()),
        _react2.default.createElement(
          'li',
          { className: nextClasses },
          _react2.default.createElement(
            'a',
            { onClick: this.handleNextPage,
              className: this.props.nextLinkClassName,
              href: this.hrefBuilder(this.state.selected + 1),
              tabIndex: '0',
              onKeyPress: this.handleNextPage },
            this.props.nextLabel
          )
        )
      );
    }
  }
```

Something here ends up calling a function in React's index.js file's `createReactFragment(object)` where the "object" passed in is undefined.

The undefined doesn't cause any issues until later down the line:

`(0, _reactAddonsCreateFragment2.default)(this.pagination())` => object ???

One question (since I am a bit confused by stepping through this mess of code) is whether or not "this.pagination()" is what ends up being the `undefined` object which gets passed down below like:

-> createReactFragment(object) ``
-> mapIntoWithKeyPrefixInternal(object[key], ...) `object[key] => children`
-> traverseAllChildren(children, ...)
-> invariant(...)

**ERROR:** 
```
_Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner})_ 
```

**Comment by ramusus** [comment]
Do you have any success in debugging? I'm just facing with it.

**Comment by forgo** [comment]
Sorry for the late follow-up on this. I'm sifting through some old GitHub issues and making sure I'm circling back on any unresolved items. It seems you may have already fixed this. I'm guessing this had something to do with React version differences and backwards incompatibility?
