### ISSUE TITLE
Demo does not work on "make install"

### ISSUE THREAD

**Issue by codyc4321** [AdeleD/react-paginate#170]
Hi, I will try this again a different way. The demo as listed does not work, and does not install on Ubuntu, nor Mac. It is entirely caused by the instructions listed. Here is what I did:

`cd /tmp
git clone git@github.com:AdeleD/react-paginate.git
cd react-paginate
make install`

Same as I got on mac, I get this error:

9269 silly pacote jest-config@https://registry.npmjs.org/jest-config/-/jest-config-17.0.3.tgz extracted in 291ms
9270 silly pacote whatwg-fetch@https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz extracted to /tmp/react-paginate/node_modules/.staging/whatwg-fetch-8f96133a by content address 95ms
9271 silly extract webpack-dev-middleware@1.12.0
9272 silly pacote trying webpack-dev-middleware@https://registry.npmjs.org/webpack-dev-middleware/-/webpack-dev-middleware-1.12.0.tgz by hash: sha1-007++y7dp+HTtdvgcolRMhllFwk=
9273 silly extract memory-fs@0.4.1
9274 silly pacote trying memory-fs@https://registry.npmjs.org/memory-fs/-/memory-fs-0.4.1.tgz by hash: sha1-OpoguEYlI+RHz7x+i7gO1me/xVI=
9275 silly pacote wordwrap@https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz extracted to /tmp/react-paginate/node_modules/.staging/wordwrap-60f8108c by content address 180ms
9276 verbose stack TypeError: Cannot read property 'find' of undefined
9276 verbose stack     at opts.integrity.digests.find.hash (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:262:33)
9276 verbose stack     at Array.find (native)
9276 verbose stack     at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:261:15)
9276 verbose stack     at emitNone (events.js:110:20)
9276 verbose stack     at Transform.emit (events.js:207:7)
9276 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
9276 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:102:11)
9276 verbose stack     at process._tickCallback (internal/process/next_tick.js:161:9)
9277 verbose cwd /tmp/react-paginate
9278 verbose Linux 4.4.0-38-generic
9279 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
9280 verbose node v8.0.0
9281 verbose npm  v5.0.0
9282 error Cannot read property 'find' of undefined
9283 verbose exit [ 1, true ]

As stated before, I automatically assume a repo is broken and doing to waste my time when the demo doesn't work, and the output is 9283 lines long anyway, so I had moved on. I would appreciate, in general, instructions listed in public repos that come up on an npm search to either work, or for the author to remove those instructions if they don't work. If the repo is not being maintained, it should be stated at the top of the README. I will gladly try to fix it if someone will tell me where to start and explain how it works.

The fact that these instructions are still in the README after I raised the issue the first time is somewhat proving my original point.

**Comment by mundosk8** [comment]
I cloned it, and works fine on macOS

**Comment by AdeleD** [comment]
Your problem has nothing to do with this package. 
It seems to be a problem with node v8.0.0 and npm v5.0.0. See the discussion here: https://github.com/npm/npm/issues/16677
Try to run `npm cache verify` and see if it works.
