### ISSUE TITLE
Go to top of page on pagination link click

### ISSUE THREAD

**Issue by Mikeg542** [AdeleD/react-paginate#173]
I have my pagination at the bottom of a table with 100ish rows, showing 12 at a time. When switching the page currently being viewed, the user is kept at the bottom of the page, which is very unfriendly for viewing all the results in the table.

```
handlePageClick = (paginate) => {
        Service.get(`${window.apiBase}/api/people`,
            (status, data) => {
                this.setState({ <values being set in state> });
        }, { page: paginate.selected + 1, limit: 12 });
        ......
    }
```

Can I add something to the paginate component or this function to return the user to the top of the webpage on pagination change.

**Comment by AdeleD** [comment]
I think you should be able to do this in the provided callback `onPageChange`.
Example:
```javascript
export class App extends Component {

  // ...

  handlePageClick = (data) => {
    // Return the user to the top of the webpage...
  };

  render() {
    return (
      <div>
        <ReactPaginate 
          previousLabel={"previous"}
          nextLabel={"next"}
          pageCount={this.state.pageCount}
          onPageChange={this.handlePageClick} />
      </div>
    );
  }
};
```

**Comment by djpowers** [comment]
In case it's helpful for anyone else, I simply added to the following to the end of the `handlePageClick` function: `window.scrollTo(0, 0)`
