### ISSUE TITLE
BreakView functionality clarification

### ISSUE THREAD

**Issue by ioanlucut** [AdeleD/react-paginate#178]
I am not sure what's the purpose of the BreakView. Currently it only allows to put a label there.

It seems to me that logic of expanding the pagination (perhaps to the right / left) while clicking isn't done.

What's the exact purpose of it ? IMHO in this shape it can't really be used. However, would be nice to have it work properly, like e.g. https://plnkr.co/edit/XTGxzKQv06OwQeXyoZaI?p=preview.

Could you please clarify it?
Many thanks.

**Comment by grbspltt** [comment]
Check your plunker link, it doesn't look like you saved your sample.

**Comment by ioanlucut** [comment]
Can you see the examples now ?

**Comment by AdeleD** [comment]
This feature has been added in version 6.0.0.
