### ISSUE TITLE
Question: How to Implement Pagination With Alphabetical Index?

### ISSUE THREAD

**Issue by zhanwenchen** [AdeleD/react-paginate#179]
Sorry to post this question as issue here, especially since the solution could be server-side. 

How could I implement pagination for alphabetically indexed content? The effect I want to achieve is like that of [IMSLP.org Composers Listing](http://imslp.org/wiki/Category:Composers) (screenshot below). 

<img width="873" alt="screen shot 2017-11-15 at 8 47 27 am" src="https://user-images.githubusercontent.com/5029736/32839424-659a3ef4-c9e2-11e7-9d69-5ab32793aefe.png">

I know the "(previous 200) (next 200)" nav could easily be switched to react-paginate out of the box, but my question is how to achieve the "A", "A cont.", and "B" indices within the data, in addition to the naive fixed_number_of_records pagination? I can also make changes to the server code.

**Comment by AdeleD** [comment]
You have to request your server with the right offset. See: https://github.com/AdeleD/react-paginate/blob/master/demo/js/demo.js#L43-L61 to understand how you can achieve that.
