### ISSUE TITLE
pagination not highliting same for top and bottom pagination

### ISSUE THREAD

**Issue by sant527** [AdeleD/react-paginate#180]
If i have two paginators top and bottom. When i click 3rd page on the top pagination the bottom pagination is not changing to 3rd

**Comment by grbspltt** [comment]
code sample?

**Comment by davelaker** [comment]
I can confirm this happens... having 2 ReactPaginate in the same component doesn't behave as expected see screenshots:

Initial Load: 
![image](https://user-images.githubusercontent.com/285474/34431248-630e11f8-ec22-11e7-91ac-80e5f38c0f42.png)

After Clicking Page 8 (on first ReactPaginate) :
![image](https://user-images.githubusercontent.com/285474/34431261-788daaac-ec22-11e7-9d9c-fde666a2ed21.png)

**Comment by castrolem** [comment]
I used `forcePage={currentPage}` attr with `currentPage` being from my components `state` and works perfectly.
