### ISSUE TITLE
Link on li vs anchor text?

### ISSUE THREAD

**Issue by grbspltt** [AdeleD/react-paginate#181]
Thank you for this great package.  Thoughts on moving the link to the `<li>` vs the `<a>`?  I have had a few users tell me the pagination is broken because they are clicking on the page box vs the page number.  I can create a PR if others see value in the change.

**Comment by alexdtru** [comment]
I 2nd this. At the least the `a` tags should get the padding from the `li` tags, so the clickable area is larger.

**Comment by AdeleD** [comment]
Yes, the link is on the `<a>` tag for accessibility reasons. See: https://github.com/AdeleD/react-paginate/issues/89.
You can make the entire page box clickable by using CSS attributes (`display: block` on `<a>` tags).

**Comment by grbspltt** [comment]
`display: block` ruins the look of my component. Admittedly CSS isn't my strong suit.
Original:
![image](https://user-images.githubusercontent.com/1534765/33281806-565880c2-d35b-11e7-9cd6-5e2e3f476a86.png)
  
With `display: block;`
![image](https://user-images.githubusercontent.com/1534765/33281869-8e0969e6-d35b-11e7-94b2-b3257e7339c7.png)

**Comment by grbspltt** [comment]
my css file
````
.paginate-container {
  display: inline-block;
  padding: 1rem;
  border-radius: .2rem;
  margin: 0.5rem;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

.paginate-container>li {
  display: inline;
  padding: 0.5rem 1rem;
}

/*.paginate-container > li > a {
  display: block;
}*/

.paginate-previous,
.paginate-next,
.paginate-page {
  border-radius: .2rem;
  margin-left: .25rem;
  margin-right: .25rem;
  border: #bbb solid 1px;
}

.paginate-previous:hover,
.paginate-next:hover,
.paginate-page:hover {
  background-color: #bbb;
}

.paginate-page.paginate-active {
  padding: 0.75rem 1.25rem;
}
.paginate-active,
.paginate-active:hover{
  font-weight: 500;
  color: #fff;
  background-color: #00BCD4;
  cursor: default;
}

.paginate-disabled:hover,
.paginate-disabled {
  background-color: #7a7a7a;
  color: #bbb;
}

.paginate-container li {
  cursor: pointer;
}
.paginate-disabled:hover{
  cursor: not-allowed;
}
````

**Comment by alexdtru** [comment]
`display: block` on the `a` tags does not solve the problem. The padding from the `li` element has to be moved to the `a` tag.

@AdeleD shouldn't this be the default behaviour?  instead of expecting everyone to fix it in their css?

**Comment by grbspltt** [comment]
I'm closing this.  While I (and one other person who has since deleted their comment) do not believe CSS is the correct way to handle this, I myself do not believe there is consensus here that anything needs to be fixed.  I'll tell my users they aren't using it properly and they should pound sand.
