### ISSUE TITLE
Add rel attribute

### ISSUE THREAD

**Issue by savva-a** [AdeleD/react-paginate#186]
Next and previous link hasn't `rel="next"` / `rel="prev"` attribute. Its may be bad for seo.

**Comment by savva-a** [comment]
Send PR #187, check it please.

**Comment by AdeleD** [comment]
Hello @savva-a,
According to the Google documentation (https://support.google.com/webmasters/answer/1663744?hl=en),  the attributes `rel="prev"` and `rel="next"` have to be added on a `<link>` tag in the `<head>` section of your website, not on the pagination itself.

**Comment by savva-a** [comment]
Ok, that was my seo-colleague's request. Issue & PR may be closed.
