### ISSUE TITLE
Generates invalid HTML

### ISSUE THREAD

**Issue by Merri** [AdeleD/react-paginate#19]
Current implementation generates `ul` and `span` elements as direct children of `ul`, which is against the spec.

**Comment by AdeleD** [comment]
There are no `span` elements as direct children of `ul` on the current version. Are you sure you're using the last one?

**Comment by mikew** [comment]
This is what I'm seeing with React v0.13.3 and the latest version of your component.

<img width="465" alt="screen shot 2015-07-29 at 12 22 39 pm" src="https://cloud.githubusercontent.com/assets/4729/8961613/9c18be9c-35ec-11e5-9c24-2f3456478c24.png">

There's definitely a `span` directly under the `ul`

**Comment by AdeleD** [comment]
Oh ok, I see. You're right, I will fix this.
