### ISSUE TITLE
Do not display next

### ISSUE THREAD

**Issue by PlayMa256** [AdeleD/react-paginate#190]
Is there a way to disable the next value if the user is currently in the last page?

**Comment by mustafawm** [comment]
similar question: is there a way to hide both previous/next buttons all together?

**Comment by PlayMa256** [comment]
@mustafawm the way that i manage to do was using css. Just targeted the .previous and .next and set the `display: none`.

**Comment by Ayush-Rawal** [comment]
You can use classNames module to add a disabled class when you're on the last page

**Comment by PlayMa256** [comment]
@shameersam conditionally lookup on the state to check which page it was, then i injected a className for it.
