### ISSUE TITLE
Active Page Number Not Reset

### ISSUE THREAD

**Issue by ranthaboy** [AdeleD/react-paginate#198]
Hi i use this to implement "Search Function" on my app
but it won't reset the active number to first page whenever i request new chunk of data
For example:
On First data loading i have 10 pages and then i move to second page,
the active class is moved to second page.
after that i do a search request and get 5 pages, the pageCount is reset,
but the active class is still on the second page, not reset to first page

This is the version i use
"react-paginate": "^5.1.0"

Thank you

**Comment by prakharcipher** [comment]
I'd like to fix this. Kindly guide me how to go with the code.

**Comment by Detachment** [comment]
Look into source code:
```javascript
componentWillReceiveProps(nextProps) {
    if (typeof(nextProps.forcePage) !== 'undefined' && this.props.forcePage !== nextProps.forcePage) {
      this.setState({selected: nextProps.forcePage});
    }
  }
```
We can know that if the forcePage number still the same, the page will re-render, but won't change. So when you do your search function, you should reset the forcePage number. In my case, I reset the forcePage number by comparing request payload( when do search function, my payload will change):
```javascript
class Pagination extends Component {
  constructor(props) {
    super(props)
    this.state = {pageNumber: 0}
  }
    componentWillReceiveProps(nextProps) {
        let pre = JSON.stringify(this.props.payload)
        let next = JSON.stringify(nextProps.payload)
        if (pre !== next) {
          this.setState({pageNumber: 0})
        }
      }
    
    render(){
        let {pageNumber} = this.state
        return(
            <ReactPaginate previousLabel={"<"}
                         nextLabel={">"}
                         breakLabel={<a className="skip" href="">...</a>}
                         breakClassName={"break-me"}
                         pageCount={pageCount}
                         marginPagesDisplayed={pagesDisplayed}
                         pageRangeDisplayed={rangeDisplayed}
                         onPageChange={this.handlePageClick}
                         forcePage={pageNumber}/>
        )
    }

}
```

**Comment by jermwatt** [comment]
> Good work around, thank you! For those wondering I just wrapped the components in a div with a changeable key.
> 
> ```
>   const [remountComponent, setRemountComponent] = useState(0);
> 
> <div key={remountComponent}>
>   <Items />
>   <ReactPaginate .../>
> </div>
> ```
> 
> And then update that state when I need to remount and go back to the first page.
> 
> ```
>     setRemountComponent(Math.random());
> ```
> 
> Thanks!

Great idea!

**Comment by murtazeventible** [comment]
> Good work around, thank you! For those wondering I just wrapped the components in a div with a changeable key.
> 
> ```
>   const [remountComponent, setRemountComponent] = useState(0);
> 
> <div key={remountComponent}>
>   <Items />
>   <ReactPaginate .../>
> </div>
> ```
> 
> And then update that state when I need to remount and go back to the first page.
> 
> ```
>     setRemountComponent(Math.random());
> ```
> 
> Thanks!

This works for me
