### ISSUE TITLE
Too few className customizations

### ISSUE THREAD

**Issue by Merri** [AdeleD/react-paginate#20]
In it's current state it is not possible to customize this component to use BEM style classes as not all generated elements have className set and some other classNames are simply forced and are not customizable (disabled, previous, next).

**Comment by lukaszklis** [comment]
:+1: for this

**Comment by AdeleD** [comment]
I have added className on each element and all class names are now customizable.
Be careful, some pre-existing props have new names, see: https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L19-L28
