### ISSUE TITLE
Error "has no default export"

### ISSUE THREAD

**Issue by hailuong123** [AdeleD/react-paginate#201]
Hi,

I use package with typescript but has issue 
_/@types/react-paginate/index"' has no default export._
i can't import module in component! please help me a resolution

**Comment by MonsieurV** [comment]
If someone could propose a PR to switch from CommonJS export (`module.exports = ...`) to the now standardized [ES6 module system](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) (`export default ...`), this would solve the issue.

**Comment by MihkelPuusepp** [comment]
When will this fix be merged?

**Comment by MonsieurV** [comment]
@AdeleD ping (the PR was updated so it can be merged)
