### ISSUE TITLE
For what jQuery as dev-dependency?

### ISSUE THREAD

**Issue by bupy7** [AdeleD/react-paginate#202]
I saw the jQuery as developing dependency and I'm having a one question: for what? :)

**Comment by MonsieurV** [comment]
Hi @bupy7,

It is used in the demo for loading dummy data: https://github.com/AdeleD/react-paginate/blob/0ddb7e07516e1b0f14880d277fb66c90ccc0aedb/demo/js/demo.js#L37

So really just for dev/demo :)

**Comment by bupy7** [comment]
@MonsieurV What about `fetch()` the native Service Worker? https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch `jQuery` in dependency just too dirty for any React extension. Or, you can just use `XMLHttpRequest` for example:

```js
let request = new XMLHttpRequest();

let params = new URLSearchParams();
params.append('limit', this.props.perPage);
params.append('offset', this.state.offset);

request.open('GET', this.props.url + '?' + params.toString(), true);

request.onload = () => {
  if (request.status >= 200 && request.status < 400) {
      let data = JSON.parse(request.responseText);
  
      this.setState({
          data: data.comments,
          pageCount: Math.ceil(data.meta.total_count / data.meta.limit)
      });
  } else {
      console.error(this.props.url, request.status, request.responseText);
  }
};

request.onerror = () => {
  console.error('Fatal error. Sorry...');
};

request.send();
```

Without jQuery...

**Comment by MonsieurV** [comment]
This is a `devDependency` and thus not used when you use the package as a library (and React component).

I'm not the author and maintainer, but I can presume jQuery was used because back then (in 2015) Fetch was not so much supported.

Anyway, this has no impact as an user of the library (only `dependencies` will be installed). I presume you can open a Pull-Request to update the demo code with Fetch.

**Comment by bupy7** [comment]
> This is a devDependency and thus not used when you use the package as a library (and React component).

Yes, of course. But if in extension the package don't use, for what it need?

> I presume you can open a Pull-Request to update the demo code to use Fetch.

Yes, later)
