### ISSUE TITLE
disabledClassName prop is broken in 5.2.0

### ISSUE THREAD

**Issue by julienben** [AdeleD/react-paginate#204]
Hi, I noticed a bug in [PaginationBoxView.js](https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js). On lines 228 and 229, you're no longer using the actual variable but a string which is always gonna be "disabled" but never the prop. Should be a very simple patch fix... Cheers!!

**Comment by MonsieurV** [comment]
Yes, my fault!

I do a regression test for it and fix it.

**Comment by AdeleD** [comment]
No problem. It's my fault too, I didn't see it when I reviewed the PR.

**Comment by MonsieurV** [comment]
Yep, tests are just better for that. (I can't really trust myself without tests.)

Maybe we should requires to merge only tested code for the next ones. :)

**Comment by julienben** [comment]
Thanks for the super fast handling!
