### ISSUE TITLE
OLD_node_modules folder really needed in npm package???

### ISSUE THREAD

**Issue by Guymestef** [AdeleD/react-paginate#208]
Hello,

I'm using react-paginate v5.2.1

When I install react-paginate, it create a folder OLD_node_modules (~45MB) inside ~/node_modules/react-paginate...
Is it really useful?

I find this out by testing offline capabilities of yarn, and so yarn is putting in its offline cache a tgz ~12MB

**Comment by AdeleD** [comment]
No, it's not useful. It's probably my fault. I think I had this folder when I released the package. I will fix this quickly. Thanks.

**Comment by AdeleD** [comment]
Should be good in v5.2.2.

**Comment by Guymestef** [comment]
It's good 👍
