### ISSUE TITLE
Breakview/Elipsis does not have required functionality

### ISSUE THREAD

**Issue by jaidi** [AdeleD/react-paginate#209]
Breakview or elipsis does not do anything. Current implementation only allows to put a label there, and that is it. 
It should ideally jump a few pages forward or backward without changing the selected page.

**Comment by Nodios** [comment]
I don't know if this is related to #232, but I still don't see it being implemented. Any news on the implementation?

**Comment by ecairol** [comment]
If you need this particular feature, the ellipsis, I recommend changing to this other plugin: http://react-component.github.io/pagination/examples/itemRender.html#5

**Comment by AdeleD** [comment]
Done in version 6.0.0.

**Comment by ecairol** [comment]
Thank you @AdeleD
