### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by matheusazzi** [AdeleD/react-paginate#21]
When I'm trying to `bower install react-paginate`, isn't this project that comes.
Can I use it with bower?

**Comment by AdeleD** [comment]
Indeed, it wasn't registered as a Bower package and, unfortunately, an other package with this name already exists.
I've just published it with the name `react-paginator`. I think you can now use it with bower but please tell me if it's not the case. Thanks.

**Comment by AdeleD** [comment]
After all, I think that can't work for the moment, sorry. It seems that some dependencies can't be satisfied.
