### ISSUE TITLE
links' default behavior

### ISSUE THREAD

**Issue by guryanov-a** [AdeleD/react-paginate#213]
Hello. I'm building a site with Gatsby static site generator and tried to use this component for the pagination on my pages. 
I need the default behavior for the links to go to another page: I generated `href` attribute for the links but had difficulties with emulating default links behavior because there are `e.preventDefault()` on all `a` elements. Workaround seems to me very complicated for such a case. Could disabling of `e.preventDefault()` on links be added as an option through props? Or maybe it can be implemented as a part of `hrefBuilder` method because there is no point to use link's default behavior without generating URL.
Or I miss some easy way to implement this?

**Comment by AdeleD** [comment]
Hello,
You can pass a function in the prop `onPageChange` to tell react-paginate what to do when a page is clicked. So, I think you can use this function to redirect the user to another page.

Example:
```javascript
<ReactPaginate
    ...
    onPageChange={(data) => {
        window.location = `/your-path/${data.selected}`;
    }}
    ...
 />
```
