### ISSUE TITLE
CSS breaking on Deployment via "react-scripts build" command

### ISSUE THREAD

**Issue by rjnitt** [AdeleD/react-paginate#215]
I am working on an application where during development the CSS of react-paginate shows up just fine, but when i deploy the app on a server(for prod) the CSS generated for "Pagination" class is missing which results in broken CSS for the directive.
Attached [image](https://imgur.com/a/VA7PMnY) here.
How to fix this?

So this is the way, i imported
import ReactPaginate from 'react-paginate'; 
Version -> "react-paginate": "^5.2.3",

<ReactPaginate
                  previousLabel={'previous'}
                  nextLabel={'next'}
                  breakLabel={<a href="">...</a>}
                  breakClassName={'break-me'}
                  pageCount={this.props.visitorTotalcount / this.props.limit}
                  onPageChange={this.handlePageClick}
                  marginPagesDisplayed={2}
                  pageRangeDisplayed={5}
                  subContainerClassName={'pages pagination'}
                  containerClassName = {'pagination'}
                  activeClassName={'active'}
                  disableInitialCallback={false}
                  />

**Comment by PlayMa256** [comment]
What is your webpack configuration? It should not be different if your config is the same.

**Comment by AdeleD** [comment]
I think this issue is not directly related to react-paginate. Your CSS file is probably not loaded correctly on your production server.

**Comment by srikanthp12** [comment]
``
