### ISSUE TITLE
Accessibility Selected <li> tabindex

### ISSUE THREAD

**Issue by mokkrb** [AdeleD/react-paginate#219]
I am running through some accessibility checks and I have notices this piece of code:

`<li class="selected"><a tabindex="0" aria-label="Page 3 is your current page" aria-current="page">3</a></li>`

The issue with that is there is no action set on the "selected" li. So when running through the page with Tab, I can see the previous, and next button selectable (and pressing enter will trigger the expected behaviour).
Is there a way to make the tabindex="-1" for the selected link ? I don't think there is any need to make it selectable, specially if no action can be performed on it.

Thanks in advance

**Comment by GLosch** [comment]
I have a similar request for setting `tabIndex="-1"` for the Previous/Next buttons when they're disabled. Happy to contribute.

**Comment by MonsieurV** [comment]
Related #273.
 
 Thanks for the suggestion @mokkrb @GLosch. This will be released on the v7.2.0
