### ISSUE TITLE
@types/react-paginate/index"' has no default export.

### ISSUE THREAD

**Issue by Englund0110** [AdeleD/react-paginate#226]
Please correct me, if this issue does not belong here. 

After updating from 5.2.3 => 5.2.4 there is no default export for index.d.ts in @types/react-paginate/

`export = ReactPaginate;` should be corrected to `export default ReactPaginate;`

**Comment by PlayMa256** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ea617ca138da2a8e2cd7528eb51cb5a0d7ee81f3/types/react-paginate/v4/index.d.ts

Send a pr to that repo.

**Comment by Englund0110** [comment]
@PlayMa256 You are linking to a v4 folder, but that contains types for react-paginate 4.3.
But this https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ea617ca138da2a8e2cd7528eb51cb5a0d7ee81f3/types/react-paginate/index.d.ts contains type definitions for the 5.2 version, and is being exported correctly. 

So as i see it, it is a problem with which of the files that are being published?

**Comment by PlayMa256** [comment]
Correct!
Nevertheless, its better to open an issue there, to ask what is going on

**Comment by Englund0110** [comment]
I've done that!

**Comment by arun-curefit** [comment]
Hi, by when will this problem be resolved?

**Comment by PlayMa256** [comment]
@arun-curefit it is a problem on definetlytyped, not on this package. This package does not exports types or anything like that

**Comment by anoopmundathan** [comment]
you can get around this by defining your own 
1. Create new declaration file , for ex: vendor.d.ts
```
declare module "react-paginate";
```
