### ISSUE TITLE
fix click event on mobile

### ISSUE THREAD

**Issue by ebrahimiaval** [AdeleD/react-paginate#227]
in mobile (browser chrome) change page dont work.

solution is change `onClick` to `onMouseDown` in `react_components/PageView.js` line 26
@AdeleD

**Comment by webcoderkz** [comment]
Make a pull request

**Comment by AdeleD** [comment]
Hello,
On version `6.5.0` of `react-paginate`, you can now define the event you want to listen onto.
You just need to instantiate the component with an `eventListener` prop.

For instance:
```javascript
<ReactPaginate eventListener="onMouseDown" />
```

Please tell me if it works for you ;)
