### ISSUE TITLE
My styles are not working

### ISSUE THREAD

**Issue by hoslack** [AdeleD/react-paginate#233]
How do I style the pagination component. I have put the classes in the options provided on the readme but I always end up with this:

<img width="573" alt="screen shot 2018-09-27 at 10 39 42" src="https://user-images.githubusercontent.com/15017978/46130330-b4fde100-c241-11e8-85af-dc399924e891.png">

**Comment by AdeleD** [comment]
Check if your CSS file is correctly loaded in your app.

**Comment by YIPG** [comment]
Ah. you guys probably used Bootstrap 4?
Use Bootstrap3 instead! It worked well for me.

ex: Insert below code into your index.html's <head>CODE</head>.
🙆‍♂ Bootstrap3
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
```
🙅‍♂ Bootstrap4
```
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
```
