### ISSUE TITLE
[5.3.0] breaks flow when its reading node modules

### ISSUE THREAD

**Issue by IljaDaderko** [AdeleD/react-paginate#245]
Out of the box for project that is using flow this errors, likely related to that line 10? easy to ignore this file, but I'm not entirely sure why flow is grabbing this .json file

> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> node_modules/react-paginate/OLD_node_modules/npm/node_modules/config-chain/test/broken.json:11:3
> 
> Unexpected string
> 
>       8│     "url": "https://github.com/dominictarr/config-chain.git"
>       9│   }
>      10│   //missing , and then this comment. this json is intensionally invalid
>      11│   "dependencies": {
>      12│     "proto-list": "1",
>      13│     "ini": "~1.0.2"
>      14│   },

**Comment by AdeleD** [comment]
Could you please try with version `5.3.1` and tell me if you have the same error?

**Comment by IljaDaderko** [comment]
Fixed, that was swift, thank you 👍

**Comment by AdeleD** [comment]
Cool! Thank you for pointing this out to me ;)

**Comment by tarunmehta-quovantis** [comment]
@AdeleD , @IljaDaderko   I am also getting same error . 
and I didn't get the solution, if you can help me out
