### ISSUE TITLE
Breaking changes in 6.0.0?

### ISSUE THREAD

**Issue by julienben** [AdeleD/react-paginate#247]
Hi, Thanks for v6.0.0. Would love to upgrade but I have no idea if there are breaking changes in the API as no changelog was provided. Any chance one of the contributors could help with this? Cheers!

**Comment by AdeleD** [comment]
Please look at the HISTORY.md
There is no real breaking changes in version 6.0.0 but if you passed a tag ´<a>´ as prop for the ´breakLabel’ you will have a warning error in the JS console, that’s why I prefered to release a major version.

**Comment by julienben** [comment]
Thanks a lot!

Maybe consider adding the content of HISTORY.md to each release in the future? It's the more traditional place to go looking for a changelog AFAIK.
