### ISSUE TITLE
`breakLinkClassName`

### ISSUE THREAD

**Issue by dosentmatter** [AdeleD/react-paginate#248]
I am using bootstrap 4 and I want to style the `<a>` tag inside the break `<li>` with the `page-item` class. A `breakLinkClassName` would be useful on [these `<a>` props](https://github.com/AdeleD/react-paginate/blob/4df9d0aa23b0e1b10dffd5b5a1313c65254f02d3/react_components/BreakView.js#L13) like this:
```
const BreakView = (props) => {
  const label = props.breakLabel;
  const className = props.breakClassName || 'break';
  const breakLinkClassName = props.breakLinkClassName || 'break-link'; // Not sure if you want to default the className to 'break-link'
  const onClick = props.onClick;

  return (
    <li className={className}>
      <a onClick={onClick}
        className={breakLinkClassName} // Set the className on the <a>
        role="button"
        tabIndex="0"
        onKeyPress={onClick}>
        {label}
      </a>
    </li>
  );
}
```

Without styling, it looks like this:
![image](https://user-images.githubusercontent.com/5732253/48861221-edb8c300-ed77-11e8-9b2d-2ebdad633f01.png)

With styling:
![image](https://user-images.githubusercontent.com/5732253/48861261-01642980-ed78-11e8-8da9-0112b5317489.png)

I saw in #182, they set `breakLabel` to an `<a>` with `className` `page-link`.
```
<ReactPaginate
  ...
  breakLabel={<a className="page-link">...</a>}
  ...
```

However, this is undesirable because you get nested `<a>`
```
<li class="page-item">
  <a role="button" tabindex="0">
   <a className="page-link">...</a>
  </a>
</li>
```

Another way would be just to use `<span>`:
```
<ReactPaginate
  ...
  breakLabel={<span className="page-link">...</span>}
  ...
/>
```

and you get
```
<li class="page-item">
  <a role="button" tabindex="0">
   <span className="page-link">...</span>
  </a>
</li>
```

But this still isn't the recommended [bootstrap](https://getbootstrap.com/docs/4.1/components/pagination/) way, where the first child of the `<li>` should have `page-link`.
```
<li class="page-item">
  <a class="page-link" href="#">3</a>
</li>
```

My current workaround is to define a new class in SCSS to set `page-link` on the first child.
```
.page-link-parent {
  > *:first-child {
    @extend .page-link;
  }
}
```

And then I set this class on the `breakClassName`:
```
<ReactPaginate>
  ...
  breakClassName="page-item page-link-parent"
  ...
/>
```

**Comment by MartinShishkov** [comment]
Did this ever got resolved?

**Comment by AdeleD** [comment]
I've just added the possibility to define a classname for the break link (`<a>`) in version `react-paginate@6.2.0`.
So now, you can do something like that:
```javascript
<ReactPaginate breakLinkClassName="page-link" />
```
