### ISSUE TITLE
First page called twice or pagination active class one step ahead.

### ISSUE THREAD

**Issue by saleem-git** [AdeleD/react-paginate#252]
react-paginate": "^6.0.0
My Pagination start at 1 and not 0, so I've set the initial page prop to 1, but now  the active page is set to '2' instead of '1' and clicking on 'Next' gets the first page again.

```
handlePageClick(data) {
// on initial page load {selected: 1}
    let param = {
      colListPage: data.selected
    };
    let collListPromise = getCollectionService.getCollList(param);
    collListPromise.then(
      res => {
        let datalist = {};
        datalist = res.data;
        this.setState({
          result: datalist.results,
          count: datalist.count
        });
      },
      error => {
        debugger;
        console.log(error);
      }
    );
  }
```

My react-paginate code

```
<ReactPaginate
            previousLabel={"previous"}
            initialPage={1}
            nextLabel={"next"}
            forcePage={1}
            breakLabel={"..."}
            breakClassName={"break-me"}
            pageCount={count}
            disabledClassName={"secondary"}
            marginPagesDisplayed={2}
            pageRangeDisplayed={5}
            onPageChange={this.handlePageClick}
            containerClassName={"pagination"}
            subContainerClassName={"pages pagination"}
            activeClassName={"active"}
          />
```

The current page is set to '2' it should be '1'  
`aria-label="Page 2 is your current page"` 

When I click on 'Next' the 'active' class moves one step ahead, it is now on '3' but the pagination is on page '2'

Note: I tried calling the the API in componentDidMount still the same issue

**Comment by AdeleD** [comment]
Hello @saleem-git,

If you try to:
* Keep `initialPage={0}` for ReactPaginate
* Remove `forcePage={1}` for ReactPaginate
* Pass `data.selected + 1` to the API like this:
```javascript
// ...
let param = {
    colListPage: data.selected + 1
};
let collListPromise = getCollectionService.getCollList(param);
// ...
```

Does it work?

**Comment by saleem-git** [comment]
Hi, 
Sorry for the late reply. 
It works, thank you for your gracious help, it works flawlessly 😄 . Why couldn't I see that? 🤦‍♂️

**Comment by AdeleD** [comment]
:wink:
