### ISSUE TITLE
 Failed prop type: Invalid prop `breakLabel` of type `object` supplied to `BreakView`, expected `string`.

### ISSUE THREAD

**Issue by abenchi** [AdeleD/react-paginate#256]
I have this warning in the code which started since the last update to the 6 release

it comes from here https://github.com/AdeleD/react-paginate/compare/v6.0.0...master#diff-8391679e244dd657bdc065ab7ae0b236R43

As you can see the `breakLabel` in 
* `BreakView`  is specified as `breakLabel: _propTypes2.default.string.isRequired,`
* However in `PaginationBoxView.` it is secified as ` breakLabel: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),`

And finally here
 https://github.com/AdeleD/react-paginate/blob/b598e17b439fa5bfb2ac687d3ef080b4de3ce309/react_components/PaginationBoxView.js#L261  
we pass the `breakLabel` from  `PaginationBoxView.` which allow node to `BreakView`  that allows only string

The fix is to modify this line https://github.com/AdeleD/react-paginate/blob/b598e17b439fa5bfb2ac687d3ef080b4de3ce309/react_components/BreakView.js#L26 to allow node

**Comment by AdeleD** [comment]
You're right. Thank you for pointing that out.
I've made a comment on your PR.
