### ISSUE TITLE
Page button remains disabled after page reload

### ISSUE THREAD

**Issue by Pablo2904** [AdeleD/react-paginate#258]
Hello,
I moving to page 2 with pagination, then on Page 2 i click into filter, which filtering prodcusts and moving me back to page  1. Unfortunetly pagination button to page 2 remain disabled.
How to make that disabled button reset to initial state?
"react-paginate": "^5.2.3",

**Comment by AdeleD** [comment]
Could you please show me your code?
Are you sure you set the `pageCount` correctly?

**Comment by MonsieurV** [comment]
We'll need a MWE to reproduce this issue. I close it in the meantime.
