### ISSUE TITLE
I can't change the selected page

### ISSUE THREAD

**Issue by tamer-axlr8** [AdeleD/react-paginate#262]
The problem happens when i want to change the page of the component without clicking on it, there are many times when you need to do that, right now i do that with ref which is not a good practice is there any other way to do that ?

**Comment by dougmackenzie** [comment]
I just ran into the same thing. Looks like the `forcePage` prop is designed to solve this. Create a state property for your current page, pass it into react-paginate, and update as required.

```jsx
<ReactPaginate forcePage={this.state.currentPage} />

// Change to first page
this.setState({
  currentPage: 0
});
```
