### ISSUE TITLE
Add property to allow custom breakLabel behaviour

### ISSUE THREAD

**Issue by Mairu** [AdeleD/react-paginate#263]
In version 5 of this package I used a link with custom change page handling logic provided as breakLabel.

Starting with version 6 this is not possible anymore.
So it would be nice if it would be possible to provide custom breakLabel click handling.

**Comment by kstratis** [comment]
Bumped into the same issue today. 

I just used the `e.stopPropagation()` and shimmed in my custom behaviour...

**Comment by AdeleD** [comment]
I'm not sure to understand what you're trying to do but you could probably use the `onPageChange` prop. No?

**Comment by Mairu** [comment]
The `onPageChange` prop is called for every page change. The custom logic I was referring to is a popup where you can enter the page number you want to jump to.

As kstratis has stated, with the usage of e.stopPropagation it is possible to prevent the onPageChange prop to be called when clicking the node which you can set as breakLabel. Although you can only use text node elements (at least to the browser warnings, because the breakLabel is nested in an a element).

Because there is this workaround I could understand to not implement that "feature".

**Comment by AdeleD** [comment]
Ok, I see what you mean.

**Comment by MonsieurV** [comment]
Hi,

You can now use the callback `onClick`, which will expose several data about what has been clicked on the the component.

For eg when you click a break element:

![image](https://user-images.githubusercontent.com/1753348/144528290-9e103a75-2419-4d95-be87-d81baa6405b4.png)

In your case you can use the `isBreak` property to detect a click on a break, and then return `false` to prevent any page change to take place. This will give something like that:

```jsx
<ReactComponent
    onClick={(clickEvent) => {
       if (clickEvent.isBreak) return false;
    }
/>
```

You can also control the page to jump to by returning a number. Returning nothing or `undefined` let the default behavior happen.

------

You can test it with:

```
npm install --save github:AdeleD/react-paginate#v8.1.0 
```

------

@AdeleD could we release v8.0.3 and v8.1.0 to NPM?
They are [tagged](https://github.com/AdeleD/react-paginate/releases).
Thx!
