### ISSUE TITLE
sometimes displays 'break' when it should just have a page number

### ISSUE THREAD

**Issue by Chuckv** [AdeleD/react-paginate#270]
In some situations (I'll try to attach screenshots and a gif) the control will display the break symbol in place of a single page number, which makes no sense.

Worse, this can turn off and on as you page through the page.  10 pages might be a magic number here.  Starting on page 1, 7 is replaced by break, but moving to page 5 or so and it displays all numbers. Then on page 6, the break moves to replace just page 3.    . 
![paging break vs number](https://user-images.githubusercontent.com/1170216/57030697-70349100-6bfa-11e9-8f9d-14d7077bafe0.png)
![paging-10-pages](https://user-images.githubusercontent.com/1170216/57030723-91957d00-6bfa-11e9-9e9b-b38a586658e0.gif)

**Comment by rotimi-babalola** [comment]
Hello @Chuckv do you have any workarounds for this issue?

**Comment by Chuckv** [comment]
Nope

**Comment by MonsieurV** [comment]
Hi @Chuckv & all!

Thanks for the report.

To test it until the `v7.2.0` is released:

```sh
npm install --save github:AdeleD/react-paginate#master
```

**Comment by Chuckv** [comment]
Thanks on behalf of anyone else expected to automate against that UI
element.   I’ve since moved on to other things, but I’m sure others will
appreciate the fix.
