### ISSUE TITLE
[feature] additional props for disable focus on activePage

### ISSUE THREAD

**Issue by eleven4y** [AdeleD/react-paginate#273]
Add prop for unset tab index on active page. 
This feature allow to achieve adequate behavior when switching between pages using the tab.

**Comment by MonsieurV** [comment]
I didn't merge the PR, as we have already a lot of props, the documentation starts to be cumbersome.

Maybe what we should do is disable the tab index for the active page, as it is not clickable. Like what we do with previous / next controls when they're disabled.

**Comment by MonsieurV** [comment]
Please re-open if you have suggestions on this.
