### ISSUE TITLE
Changing containerClassName from pagination removes all built in styles

### ISSUE THREAD

**Issue by Spence1115** [AdeleD/react-paginate#275]
The styles that come by default with react-paginate are no longer added if I change the default containerClassName from 'pagination' to anything else. They should be tied to whatever class I change it to, otherwise I'm locked into using that class regardless.

**Comment by SnarkieDesign** [comment]
I wasn't aware it shipped with any default styles?

**Comment by CallumHemsley** [comment]
There is no default styles.
