### ISSUE TITLE
Unclickable links

### ISSUE THREAD

**Issue by SeanDez** [AdeleD/react-paginate#277]
In a fresh install of create-react-app (version 2.1.1 with React version 16.9.0) the following code produces unclickable links that are also displayed vertically with list bullets:

```
import ReactPaginate from 'react-paginate';

function App() {
  return (
    <div className="App">
      <header contents removed... >

      <ReactPaginate
        pageCount={8}
        onPageChange={e => console.log(e, `=====e=====`)}
        marginPagesDisplayed={2}
        pageRangeDisplayed={2}
      />
```
Image: https://s.nimbusweb.me/attachment/3337503/lhze12fh65x62tk8bp1k/ajftA9o9WXJaGC6S/Screenshot_2019-09-20_18.53.32.jpg

Problem was first seen in a real project and then replicated here.

It does NOT happen when git cloning the demo and using the <ReactPaginate /> component with props shown above, which makes me believe a recent library bug may be the issue. In the demo, using the above, the links are unstyled but clickable. They appear horizontally as you would expect.

**Comment by sparksparker** [comment]
having the same issue as you. 

has anyone else run into this issue/able to figure out why it's not working/how to fix it?

**Comment by dhruvikn** [comment]
Use CSS to style pagination elements. An example with bootstrap will look like -
```jsx
<ReactPaginate
    previousLabel={"«"}
    nextLabel={"»"}
    breakLabel={'...'}
    breakClassName={'break-me'}
    pageCount={this.state.pageCount}
    marginPagesDisplayed={2}
    pageRangeDisplayed={5}
    onPageChange={this.handlePageClick}
    containerClassName={'pagination'}
    pageClassName="page-item"
    previousClassName="page-item"
    nextClassName="page-item"
    pageLinkClassName="page-link"
    previousLinkClassName="page-link"
    nextLinkClassName="page-link"
    activeClassName="active"
/>
```

which will render the pagination component like [this.](https://getbootstrap.com/docs/4.3/components/pagination/) Don't forget to include bootstrap.
