### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by goxr3plus** [AdeleD/react-paginate#282]
@AdeleD  Adele you don't reply to any issues and we are having problems here .

**Comment by entozoon** [comment]
Oof, is it? Do you know an alternative. I'm getting a `PaginationBoxView.js Module not found: Error: Can't resolve 'react'` error, so this is a dead end

**Comment by goxr3plus** [comment]
Bro you forgot to `import react` somewhere .

**Comment by entozoon** [comment]
Oh crumpets, yeah cheers. I'm infernoing and didn't realise. Still, I'll give [rc-pagination](https://www.npmjs.com/package/rc-pagination) a go instead.. seems the popular choice.

**Comment by goxr3plus** [comment]
@entozoon  :) Yep Brusky!

**Comment by entozoon** [comment]
Yah bruh!

**Comment by webcoderkz** [comment]
@entozoon i didn't liked rc-pagination, this component is more customizable.

**Comment by entozoon** [comment]
@webcoderkz Agreed, I'd use it again in full React. For my Inferno issues, in the end I just built my own pagination component.. which wasn't as difficult as I thought, but you know.. bespoke ballacheness.

**Comment by AdeleD** [comment]
It is alive.
