### ISSUE TITLE
Is there any option to make pagination with API?

### ISSUE THREAD

**Issue by cptiwari20** [AdeleD/react-paginate#289]
I want to create pagination for based on API?
Eg: we have a large data of reviews which I want to render on the frontend. We have an API like `/user/review/show/${user.id}/${page_number} `. Every request returns the data of 10 reviews and also return the total number of data in the database;
here the total reviews it 190 and we are getting 10 on each page.
```
count: 190
user_id: 1
reviews: (10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
__proto__: Object
```

Please suggest some way that how can we implement it on our react-paginate.

**Comment by dominiceden** [comment]
Hi @cptiwari20 I've successfully got this to work very nicely with a Rails 5 API server. You will need your backend to send headers on the total number of pages and which page you are on. I'm using the `api-pagination` gem for this, which allows me to paginate a collection/array of items using offsets (an offset is basically a page number). 

The gem then sends the number of items per page and the total number of items  to the client in the headers. In the client, I read these headers and pass them to ReactPaginate. 

Hope that helps.

**Comment by cptiwari20** [comment]
> Hi @cptiwari20 I've successfully got this to work very nicely with a Rails 5 API server. You will need your backend to send headers on the total number of pages and which page you are on. I'm using the `api-pagination` gem for this, which allows me to paginate a collection/array of items using offsets (an offset is basically a page number).
> 
> The gem then sends the number of items per page and the total number of items to the client in the headers. In the client, I read these headers and pass them to ReactPaginate.
> 
> Hope that helps.

Thank you @dominiceden for your valuable suggestion.
I have created one for me, please test it out, I hope it would be helpful for you.
https://www.npmjs.com/package/react-api-pagination

**Comment by dominiceden** [comment]
Hi @cptiwari20 thanks for releasing it. I'm fairly happy with my current setup but will keep yours in mind if I need to change!
