### ISSUE TITLE
Handle page click in sample makes two ajax requests instead of one

### ISSUE THREAD

**Issue by juanda99** [AdeleD/react-paginate#29]
Line 68 should be deleted, file sample.jsx:
  
    handlePageClick = (data) => {
        let selected = data.selected;
        let offset = Math.ceil(selected * this.props.perPage);

        this.setState({offset: offset}, () => {
          this.loadCommentsFromServer();
        }.bind(this));

       //Line 68:  this.loadCommentsFromServer();
      }

**Comment by AdeleD** [comment]
Fixed. Thank you!
