### ISSUE TITLE
how to create aria-label when using icons for prev/next

### ISSUE THREAD

**Issue by BernardA** [AdeleD/react-paginate#299]
I tried several iterations of your `ariaLabelBuilder` prop to generate `aria-label` for the prev/next buttons, where I use `material-ui` icons.

Currently they look like:

      previousLabel={() => <div className={stylesPagination.paginationNav}><NavigateBeforeIcon /></div>}
      nextLabel={() => <div className={stylesPagination.paginationNav}><NavigateAfterIcon /></div>}

Placing the `aria-label` attribute directly at the labels props will not solve the issue, as it those are children elements to the `a tag` that requires the `aria-label`.

**Comment by AdeleD** [comment]
Currently, you can't add an aria-label easily on prev/next buttons. We should implement it.

**Comment by GLosch** [comment]
FYI to anyone who finds this in the future. aria-labels were added with default values and override props as of [version 6.4.0](https://github.com/AdeleD/react-paginate/blob/master/CHANGELOG.md#-640): `nextAriaLabel` and `previousAriaLabel`.

@AdeleD you can probably close this ticket
