### ISSUE TITLE
Invalid prop `breakLabel` supplied to `PaginationBoxView`, expected a ReactNode

### ISSUE THREAD

**Issue by lauterry** [AdeleD/react-paginate#30]
Hi

I used the versino 0.4.1 and copy your provided example.

I got the following warning :

```
Warning: Failed propType: Invalid prop `breakLabel` supplied to `PaginationBoxView`, expected a ReactNode. Check the render method of `TableBox`.

Uncaught Error: Invariant Violation: PaginationBoxView.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

What's the purpose of breakLabel by the way ? Is it a ReactNode or a String ? 

Best regards

**Comment by AdeleD** [comment]
Hi,

Indeed the `breakLabel` is defined as a `React.PropTypes` of type `node` which means that anything can be rendered through this prop (including strings or HTML elements).

It allows you to set a breakLabel like `...` or `<a href="">...</a>` for instance if you want the `breakLabel` to be a link.

**Comment by lauterry** [comment]
Hi

Thank for your explanations.

Still, I encountered the warnings.

Any idea ?

**Comment by AdeleD** [comment]
Can you show me your `breakLabel` please? Is that a string?

**Comment by lauterry** [comment]
Same as in this file : https://github.com/AdeleD/react-paginate/blob/master/sample/sample.jsx

**Comment by AdeleD** [comment]
Ok, so this seems very strange. Maybe the problem is somewhere else in the render method of your TableBox component? I don't really know but if you show me your render method maybe I could help...

**Comment by keoshi** [comment]
Same here, I'm using the exact code from your example and getting the same error.

`Warning: Failed propType: Invalid prop `breakLabel` supplied to `PaginationBoxView`, expected a ReactNode.`

**Comment by ShankarSangoli** [comment]
clicking on breakLabel which is set to `breakLabel={ <li className='break'><a href=''>...</a></li> }` just reloads the page. Why doesn't it invoke the clickCallback?
