### ISSUE TITLE
Why does it display an inconsistent number of pages?

### ISSUE THREAD

**Issue by sinnerJoe** [AdeleD/react-paginate#300]
When I'm on page 1 it displays 5 pages:
![image](https://user-images.githubusercontent.com/16450547/78371478-b21b4380-75d0-11ea-805d-a3a41ef3f6ce.png)

But when I go to the last page it shows only 4:
![image](https://user-images.githubusercontent.com/16450547/78371531-c52e1380-75d0-11ea-90d4-93ed7294daad.png)

*Configurations:*

pageRangeDisplayed = 3
marginPagesDisplayed= 1

**Comment by MonsieurV** [comment]
Seems to have been fixed (certainly from #302)

![image](https://user-images.githubusercontent.com/1753348/140183857-d3785f8c-d0d4-4182-8c0e-ce414dcb3bc9.png)

with (on the demo)

```js
        <ReactPaginate
          ...
          pageCount={11}
          marginPagesDisplayed={1}
          pageRangeDisplayed={3}
        />
```

Before the `v7.2.0` is released, you can test and  install from GitHub:

```sh
npm install --save github:AdeleD/react-paginate#master
```

Please re-open with a code sample / MWE if you still have issues

Thanks for the report @sinnerJoe
