### ISSUE TITLE
Provide the CSS from the examples in the documentation

### ISSUE THREAD

**Issue by yasuf** [AdeleD/react-paginate#306]
## Request
Is it possible to share the CSS that was used on the example on the homepage?

**Comment by anthonyk1225** [comment]
Here's a gist of my attempt to copy the first example in the docs - https://gist.github.com/anthonyk1225/73e5547d55c3c9c2450fac7daa667e31

**Comment by AdeleD** [comment]
Do you mean the first two examples appearing on the README.md?
I can't, sorry. Because I've created them for a company I worked for.

(The example of the demo uses bootstrap https://getbootstrap.com/docs/4.0/components/pagination/).

**Comment by jermwatt** [comment]
> Here's a gist of my attempt to copy the first example in the docs - https://gist.github.com/anthonyk1225/73e5547d55c3c9c2450fac7daa667e31

fantastic!
