### ISSUE TITLE
Allow devs to disable the break ("..." / ellipsis) click action.

### ISSUE THREAD

**Issue by leodutra** [AdeleD/react-paginate#309]
For some companies (like mine), it's important that the user sees every page sequentially...
but still, be aware there's a multitude of pages back/forward.

Please allow us, devs, to pass some [handleBreakClick](https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L140) or disable the clickability.

**Comment by Norange88** [comment]
@leodutra you can add absolutely positioned pseudo-element to the break button that will block user from clicking the inner link

```
li.break::after {
    display: block;
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    z-index: 3;
    width: 100%;
    height: 100%;
    cursor: default;
  }
```

Hope this is what you are looking for

**Comment by leodutra** [comment]
Thanks, @Norange88, that will work for now :smile:
