### ISSUE TITLE
Automatic pageRangeDisplayed count

### ISSUE THREAD

**Issue by DeOne4eg** [AdeleD/react-paginate#319]
I would like the width not to change during page switching. Example https://codesandbox.io/s/99fh2. Is it possible to do this now or is the author's intervention required?

**Comment by AdeleD** [comment]
You can do this with CSS.

**Comment by tonthanhhung** [comment]
This is my work around solution 
```
marginPagesDisplayed={1}
pageRangeDisplayed={page + 1 <= 3 ? 4 : totalPages - page <= 3 ? 5 : 3}
```
