### ISSUE TITLE
Support for React 17.0+?

### ISSUE THREAD

**Issue by SaitamaSama** [AdeleD/react-paginate#330]
The peer dependency for the project is React@^16. This results in this library not being compatible with React 17.0+.
Can we have React 17 support for this library?

Since React 17 is backward compatible with ^16 the transition should be smooth.
Currently trying to install `react-paginate@7.0.0` results in this peer-dep error:
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-paginate@7.0.0
npm ERR! node_modules/react-paginate
npm ERR!   react-paginate@"*" from the root project
```

Thanks.

**Comment by rafipiccolo** [comment]
could u change this in the package.json to allow react v17 ?

i can confirm that it works for me with react 17, if i force install, but it would be better to just install without force.

```
"peerDependencies": {
    "react": "^16.0.0"
},
```
it could be

```
"react": "^16.0.0 || ^17.0.0",
"react-dom": "^16.0.0 || ^17.0.0"
```

**Comment by rafipiccolo** [comment]
pull request done, could u merge it please ?

**Comment by pawel2105** [comment]
Workaround: `npm i react-paginate --legacy-peer-deps`

**Comment by AdeleD** [comment]
Done in https://github.com/AdeleD/react-paginate/pull/331
