### ISSUE TITLE
Initial page is not working as expected

### ISSUE THREAD

**Issue by kaisian97** [AdeleD/react-paginate#338]
![image](https://user-images.githubusercontent.com/26655111/108183314-ecd48e80-7144-11eb-8f3e-5f9b5b1c606a.png)
![image](https://user-images.githubusercontent.com/26655111/108183378-f827ba00-7144-11eb-995c-19bc7af65cf2.png)
Version: 7.1.0
Expected: Highlight 11
Actual: Highlight on seperator

**Comment by AdeleD** [comment]
If you want some help, please show us how you pass the page to the react-paginate component.

**Comment by kaisian97** [comment]
> If you want some help, please show us how you pass the page to the react-paginate component.

I created a minimal codesandbox. You can have a look, I guess it is related to the nextjs ssr.
https://codesandbox.io/s/stoic-meninsky-luwcv?file=/pages/index.js
