### ISSUE TITLE
If I click back on 5th page it reset pagination to first page

### ISSUE THREAD

**Issue by yousufkalim** [AdeleD/react-paginate#344]
Hi,
If i try to use back button on browser not go on previous page on pagination but go to the page before the pagination

**Comment by venugopaal** [comment]
yes i am also faceiing same iisue

**Comment by yousufkalim** [comment]
> yes i am also facing same issue

We have to use pagination with queries in url bar.

**Comment by AdeleD** [comment]
> We have to use pagination with queries in url bar.

Indeed. Your issue is not directly related to this package.
