### ISSUE TITLE
How to set current page?

### ISSUE THREAD

**Issue by ap13p** [AdeleD/react-paginate#35]
Let say I was typing directly in the urlbar to page 6, how I am supposed to pass this page number to ReactPaginate? Because it is always start at 1

**Comment by AdeleD** [comment]
Hi,

You can pass the page number from url to ReactPaginate with prop `initialSelected`:

```javascript
<ReactPaginate 
previousLabel={"previous"}
nextLabel={"next"}
initialSelected={6}
clickCallback={this.handlePageClick} />
```

**Comment by ap13p** [comment]
Ok thanks

**Comment by maxfarseer** [comment]
can't set this from props...
I try to reset page to '1' after sorting records.
Example: sort = city, page 8 => sort = country, page 1 (in this.props), but not in ReactPaginate (

**Comment by younes0** [comment]
@maxfarseer I have the same issue. Did you find a workaround ?

**Comment by maxfarseer** [comment]
@younes0 no :(

**Comment by AdeleD** [comment]
Which version of react-paginate do you use?

**Comment by younes0** [comment]
2.1.1

**Comment by itsazzad** [comment]
How to make `initialSelected` dynamically in run time?

**Comment by EllisMin** [comment]
You can use `forcePage` property instead of `initialPage` to watch for changes

**Comment by MLazarevic36** [comment]
> 
> 
> You can use `forcePage` property instead of `initialPage` to watch for changes

Also, make sure that your prop is parsed as int 😄

**Comment by trungle11** [comment]
> can't set this from props...
> I try to reset page to '1' after sorting records.
> Example: sort = city, page 8 => sort = country, page 1 (in this.props), but not in ReactPaginate (

Sir, do you know how to fix it? I have the same problem
