### ISSUE TITLE
Next button doesn't add 'disabled' class

### ISSUE THREAD

**Issue by charles-jordan-aslarona** [AdeleD/react-paginate#352]
Hi Adele,

The previous button currently uses 'disabled' class when the active page is the first one.
However for some reasons, the next button doesn't add next button even if the last page is currently the active one.
I will appreciate your help. Attached are the screenshots and code snippet.

**1st page is active (Previous is disabled)**
![image](https://user-images.githubusercontent.com/81416184/112618514-2b0a4f80-8e61-11eb-96c1-975b9b918537.png)

**Last page is active (Next is not disabled)**
![image](https://user-images.githubusercontent.com/81416184/112618645-4e34ff00-8e61-11eb-833b-9cd0fdde364a.png)

**Code**
![image](https://user-images.githubusercontent.com/81416184/112618668-568d3a00-8e61-11eb-9b23-7fa75d6ecb31.png)

Thank you

**Comment by Juli1en** [comment]
> The previous button currently uses 'disabled' class when the active page is the first one.

Looks like this happens when you pass a number with decimal value in the props "pageCount". 
Actually rounding the number fixed that issue for me
I would recommend you to change your code like this :

`pageCount={ Math.ceil(this.state.billers.length / 15) }`

**Comment by fatihaslantas** [comment]
setting empty string to previousLabel and nextLabel would also solve the issue. 

previousLabel={pageCount > 0 ? '<' : ''}
nextLabel={pageCount > 0 ? '>' : ''}

**Comment by MonsieurV** [comment]
There will now be a warning when a float is provided as `pageCount`, this will make these issues easier to debug.
Please use at least the [v7.1.5](https://github.com/AdeleD/react-paginate/releases/tag/v7.1.5) for that.

Thanks for the report!

**Comment by KangYoosam** [comment]
I've encountered same experience.

Thanks @charles-jordan-aslarona to issuing this, and thanks @Juli1en to answer!
