### ISSUE TITLE
React throws warnings after updating to 0.4.2

### ISSUE THREAD

**Issue by ingro** [AdeleD/react-paginate#36]
Hello! I'm using your library and after updating to the latest version (0.4.2) I got alot of this warnings on page load:

```
Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

I guess the problem is that the `clickCallback` is now called also on initialization. That cause me problems because I'm using the paginator on a table whose items are loaded via an ajax call. Calling the `clickCallback` will cause another action to be emitted which loads the items with a new `page` property's value. How it is possible to avoid this? Couldn't be added a boolean props (default to true) which tells the Paginate Component to or not to call the `clickCallback` on initialization?

Thanks.

**Comment by AdeleD** [comment]
Thank you for pointing that out. The `clickCallback` method is now called into the method `componentDidMount`. I've also added a condition on this call, I think it could fix your problem with ajax but please tell me if it's not the case. Thanks.

**Comment by ingro** [comment]
Thanks, now the warning is gone! :)

**Comment by AdeleD** [comment]
Ok! :)
