### ISSUE TITLE
Only PREVIOUS | NEXT pages

### ISSUE THREAD

**Issue by DesmondM** [AdeleD/react-paginate#367]
Is there a way of disabling the display of pages and just have two buttons  PREVIOUS | NEXT ?

**Comment by MonsieurV** [comment]
Hi @DesmondM,

With v8.1.0 you do:

```js
<ReactPaginate
     pageRangeDisplayed={0}
     marginPagesDisplayed={0}
     containerClassName="pagination-widget"
     activeClassName="active"
/>
```

This will show only the active page.

Then add above some simple CSS to it the active page:

```css
.pagination-widget a.active {
     display: none;
}
```

This will be simpler than to add still another option/prop.

-----

PS. To get the v8.1.0 before its release you can do:

```console
npm install --save github:AdeleD/react-paginate#v8.1.0
```
