### ISSUE TITLE
clickCallback gets called during initialization

### ISSUE THREAD

**Issue by nbwar** [AdeleD/react-paginate#39]

**Comment by agat** [comment]
This bug is still in 0.5.4 version.

**Comment by zirho** [comment]
:+1: +1

**Comment by AdeleD** [comment]
When you instanciate the ReactPaginate component with prop `initialSelected`, the `clickCallback` is called during initialization to allow you to load the appropriate content (depending on the selected page).

Could you please explain to me why you didn't expect this behavior?

**Comment by beholderrk** [comment]
This is not obvious behaviour. For example
```javascript
class SomeList extends Component {
    componentDidMount () {
        this.props.dispatch(fetchItems())
    }

    changePage(data) {
        this.props.dispatch(fetchItems(data.selected));
    }

    render() {
        let pagingProps = pick(this.props.data, ['pageNum', 'current']);
        return (
            <div>
                <div className="list">
                    ... render list from this.props.data.items ...
                </div>
                <div className="footer">
                    <Pagination {...pagingProps} clickCallback={this.changePage.bind(this)}></Pagination>
                </div>
            </div>
        );
    }
}
```
As result we have 2 call fetchItems when SomeList initializing.
When componentDidMount and when Pagination initializing.
Unexpectedly that the click event raised when Pagination initializing.

**Comment by hackingbeauty** [comment]
+1 experiencing the same issue here.

**Comment by jedrichards** [comment]
Yep I don't think this is right. The component shouldn't make any assumptions on logic happening in the outer app. I'd imagine in the vast majority of cases data has already been fetched before the component is shown?

It's easy to make sure the initial page of results has been fetched, but it's hard to work around the component trying to do it for you ...

**Comment by hozefaj** [comment]
Why is the issue closed? Facing the same problem. It seems unnecessary that callBack function is invoked during initialization.
