### ISSUE TITLE
how to prevent useState from resetting pagination

### ISSUE THREAD

**Issue by Cyroen** [AdeleD/react-paginate#393]
how do i prevent useEffect from activating inside the function when i use useState()?

**Comment by MonsieurV** [comment]
Hi @Cyroen,

Please post sample code to reproduce the issue that's affecting you.

https://en.wikipedia.org/wiki/Minimal_working_example

**Comment by Cyroen** [comment]
const [servantDetail, setservantDetail] = useState({
      name: "",
      class: "",
      rating: "",
      CStar: "",
      CAbsorb: "",
      CDamage: "",
      QDmg: "",
      ADmg: "",
      BDmg: "",
    });
    function Items({ currentItems }) {
    return (
      <>
        {currentItems &&
          currentItems.map((a) => (
            <div
              className={style.profile}
              onClick={(e) => {
                document
                  .getElementById("profile_detail")
                  .classList.toggle("detail_open");
                document.getElementById("dim").classList.toggle("dimmed");
                setservantDetail({
                  name: a.name,
                  class: a.class,
                  rating: a.rating,
                  CStar: a.CStar,
                  CAbsorb: a.CAbsorb,
                  CDamage: a.CDamage,
                  QDmg: a.QDmg,
                  ADmg: a.ADmg,
                  BDmg: a.BDmg,
                });
                console.log(servantDetail);
              }}
            >
              <div>
                <img src={image} alt="" />
                <div className="mb-3">
                  <h5>{a.name}</h5>
                  <p>{a.class}</p>
                </div>
              </div>
              <div className={style.total}>
                <p>{a.rating}</p>
              </div>
            </div>
          ))}
      </>
    );
    }
   

    function PaginatedItems({ itemsPerPage }) {

    // We start with an empty list of items.
    const [currentItems, setCurrentItems] = useState(null);
    const [pageCount, setPageCount] = useState(0);
    // Here we use item offsets; we could also use page offsets
    // following the API or data you're working with.
    const [itemOffset, setItemOffset] = useState(0);

    useEffect(() => {
      // Fetch items from another resources.
      const endOffset = itemOffset + itemsPerPage;

      setCurrentItems(servants.slice(itemOffset, endOffset));
      setPageCount(Math.ceil(servants.length / itemsPerPage));
    }, [itemOffset, itemsPerPage]);

    // Invoke when user click to request another page.
    const handlePageClick = (event) => {
      const newOffset = (event.selected * itemsPerPage) % servants.length;
      console.log(
        `User requested page number ${event.selected}, which is offset ${newOffset}`
      );
      setItemOffset(newOffset);
    };

    return (
      <>
        <div className={style.delivery}>
          <Items currentItems={currentItems} />
        </div>
        <ReactPaginate
          breakLabel="..."
          nextLabel="next >"
          onPageChange={handlePageClick}
          pageRangeDisplayed={5}
          pageCount={pageCount}
          previousLabel="< previous"
          renderOnZeroPageCount={null}
          disableInitialCallback={true}
        />
      </>
    );
  }

**Comment by MonsieurV** [comment]
Please describe, step by step, what is happening that isn't expected. Which `useState()` do you think cause an issue?

You can also post a _working_ sample on CodePen. You can start from there: https://codepen.io/monsieurv/pen/abyJQWQ

**Comment by Cyroen** [comment]
https://codepen.io/Kairoseki/pen/dyzeVGm

for some reason codepen isn't showing the results,
but i think the useEffect is being triggered by another onClick event which is used by a div element

**Comment by MonsieurV** [comment]
Which `useEffect`?

This one?

```js
useEffect(() => {
  // Fetch items from another resources.
  const endOffset = itemOffset + itemsPerPage;

  setCurrentItems(servants.slice(itemOffset, endOffset));
  setPageCount(Math.ceil(servants.length / itemsPerPage));
}, [itemOffset, itemsPerPage]);
```

What does it do exactly then?

I close because I don't see so far how this is an issue with `react-paginate`.

If your example is not working, we won't debug it for you. Please follow
https://reactjs.org/docs/thinking-in-react.html
https://en.reactjs.org/community/support.html
Also please learn to [highlight](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) your code snippets (specify `js`) and use correct indentations.

**Comment by Cyroen** [comment]
yes, that `useEffect` it seems to trigger when i press onClick on a div, i was wondering how to prevent it from triggering when i click the div

**Comment by MonsieurV** [comment]
But then what it _actually_ does when it trigger? (resetting pagination: what is that?)

If it triggers, this is because `itemOffset` and `itemsPerPage` have changed.
https://en.reactjs.org/docs/hooks-effect.html

I won't help further, you'll have to think it through and first debug it on yourself. If you can't state specifically the issue, we won't be able to help here.

https://en.reactjs.org/community/support.html

**Comment by Cyroen** [comment]
@MonsieurV ok, thanks for the help
