### ISSUE TITLE
Wrong numbering in pagination

### ISSUE THREAD

**Issue by csl24** [AdeleD/react-paginate#395]
Hello!

When testing the library, I noticed that the page numbering is not correct in some cases.

![error](https://user-images.githubusercontent.com/60264862/142547541-4368eb40-e7c4-4329-a9ed-a9e40d2e97ee.png)

I found that the error is related to the implementation _"Fix the breaking algorithm to not create breaks for only one page"_ (see: [#270](https://github.com/AdeleD/react-paginate/issues/270)) in the v8.0.0, because in v7.1.3 there is no problem of enumeration.

I add a link to test the behavior: [codepen](https://codepen.io/CodeNine/pen/PoKVrGm)

**Comment by progranime** [comment]
Hi,

I've encountered the same issue.
I'm using this version.
"react-paginate": "^8.0.0"

![image](https://user-images.githubusercontent.com/20163429/143172835-1c980c11-6a32-4d09-ab72-dac514fa619e.png)
![image](https://user-images.githubusercontent.com/20163429/143173374-5032d15a-6b2c-4866-855c-cefe5a14ad56.png)

Please check on this issue.
Thanks.

**Comment by MonsieurV** [comment]
Indeed, it was utterly broken. :grimacing: 
I didn't tested it properly with many pages.

Thanks for the report @csl24 @progranime

**Comment by MonsieurV** [comment]
You can test right now the fix with:

```sh
npm install --save github:AdeleD/react-paginate#v8.0.1
```

https://github.com/AdeleD/react-paginate/releases/tag/v8.0.1
@AdeleD this could be released, as v8.0.0 is pretty broken

**Comment by AdeleD** [comment]
@MonsieurV Done

**Comment by MonsieurV** [comment]
Here the original snippet with the bug fixed (react-paginate bumped to v8.0.1): https://codepen.io/monsieurv/pen/MWvMOBE
