### ISSUE TITLE
Is there any way to style this component with CSS-in-js?

### ISSUE THREAD

**Issue by ncesar** [AdeleD/react-paginate#397]
Hi, I'm building a new paginate component using this awesome package but I need to style it. And it seems that the only way to style it is using class but I don't see to find a way to style it using css-in-js. Is there any way to do it?

**Comment by MonsieurV** [comment]
Hi @ncesar,

Please see https://github.com/AdeleD/react-paginate/issues/321#issuecomment-980352392

**Comment by ncesar** [comment]
> Hi @ncesar,
> 
> Please see [#321 (comment)](https://github.com/AdeleD/react-paginate/issues/321#issuecomment-980352392)

Hi. I see that there is a styled-components options but I was searching to do it with css in js.

**Comment by MonsieurV** [comment]
For now the lib only allows for `className` (several, actually) to be passed.

Would you find helpful a `style` prop?

Please continue the conversation on #80
