### ISSUE TITLE
Displayed questions

### ISSUE THREAD

**Issue by iBreadInside** [AdeleD/react-paginate#399]
Hello! I start to use your library and have a few questions. There is my demo: https://codesandbox.io/s/hidden-wave-fn6nl?file=/src/App.js

1. Page 1. Why I can see second item, but then I am on last position (7) I can't see the 6-th?
2. Page 3. Why I can see second item? And why then I am on 5-th pos I see 6-th? How to hide them? Only with css or js?

I need to see adjacent item only if I'm on first or last page and adjacent pages are first or last. Can you help me with that?

**Comment by MonsieurV** [comment]
I'm not sure we can help. The library is proposed "as it is".

A numbering algo has been chosen, and we can't change it to accommodate everyone.
We could in the absolute expose an API to let you determine the layering of pages, but then the library would not offer much (better just code your own directly).

Maybe you should look [the algo](https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L335), fork it and try to make a version that match your own need. Then if your kind show it to us, so we can see if it can be integrated back.

Good luck

**Comment by iBreadInside** [comment]
Yeah, but why marginRangeDisplayed=1 works different for first and last items? Seems like a bug.

**Comment by iBreadInside** [comment]
Ok, I got it. You need make handler which will change state of currentPage and use a condition for pageRangeDisplayed. Like this:

https://codesandbox.io/s/hidden-wave-fn6nl?file=/src/components/guitar-pagination.jsx
