### ISSUE TITLE
8.0.3 is latest on npm but 8.1.0 exist

### ISSUE THREAD

**Issue by rafipiccolo** [AdeleD/react-paginate#400]
version 8.0.3 is noted as latest in npm
version 8.1.0 already exist and would be the expected one, sementically speaking
is it intentionally ?

https://www.npmjs.com/package/react-paginate
see version tab

**Comment by MonsieurV** [comment]
There is just a delay before the versions are released on NPM; @AdeleD will do it as soon as it passes over there

**Comment by rafipiccolo** [comment]
just a supposition, but i though that version 8.0.3 and 8.1.0 have been built simultaneously and version 8.0.3 took longer to build and therefore got the latest tag.
ps: I am not in a hurry, only wanted to report since my CI complained.
thx

**Comment by MonsieurV** [comment]
Ah sorry, I didn't look properly on NPM.

![image](https://user-images.githubusercontent.com/1753348/145370831-5ed89522-936c-4b51-82be-8b9fbb931c63.png)

Indeed we certainly published 8.1.0 first, then 8.0.3, and NPM use the latest published by date and not semver to order them.

@AdeleD I don't know if you can manually reorder them on NPM?

Else will just to a bump to `8.1.1` to get it ahead.

**Comment by AdeleD** [comment]
I thought NPM was smart enough to know the version order, but apparently it doesn't, sorry.
I couldn't change the order in the version history, but I was able to mark version 8.1.0 as the "latest" one. So, it should be good now.

![Capture d’écran de 2021-12-09 11-54-45](https://user-images.githubusercontent.com/942068/145383693-24c015ad-2397-4b78-a161-a750c0dc7285.png)
