### ISSUE TITLE
onClick issue

### ISSUE THREAD

**Issue by devhounD96** [AdeleD/react-paginate#401]
Guys, for some reason my onclick is not working.
<Paginate
                onClick =  {(e) => {
                                    console.log('event:', e);
                        }}
                previousLabel = {"<<"}
                nextLabel = {">>"}
                pageCount = {pageCalc}
                onPageChange = {alterPage}
                containerClassName = {"paginateBtn"}
                previousLinkClassName = {"prevBtn"}
                nextLinkClassName = {"nextBtn"}
                disabledClassName = {"disabledBtn"}
                activeClassName = {"activeIndicator"}
                pageRangeDisplayed={5}
                breakLabel = {"..."}
                marginPagesDisplayed = {2}
                pageRangeDisplayed = {3}
                />

nothing is consoled.
NB: I am kind of new at this, so maybe its an obvious mistake.
please bear with me.

**Comment by MonsieurV** [comment]
Hi @devhounD96,

Which version of the package do you use?

`onClick` only appeared in [v8.1.0](https://github.com/AdeleD/react-paginate/releases/tag/v8.1.0)

PS. Check the [markdown syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to highlight code on GitHub ;-)

**Comment by devhounD96** [comment]
Hi @MonsieurV  the version is 
"react-paginate": "^8.1.0",

Thanks for the tip btw

**Comment by devhounD96** [comment]
If there is any way that can help me work around this issue, please share.
Thanks in advance.

**Comment by MonsieurV** [comment]
The best thing would be to create a GitHub repository with a running example of your code (only the relevant part) that does not work as you want. Else it is difficult for us to reproduce your issue and give you proper guidance.

**Comment by devhounD96** [comment]
Ok @MonsieurV I'll do just that and share the details here

**Comment by devhounD96** [comment]
Hi  @MonsieurV  the issue was resolved once I removed the package and installed again.
Thank you for showing  willingness to help.
