### ISSUE TITLE
how do i control the amount of pages displayed

### ISSUE THREAD

**Issue by salivity** [AdeleD/react-paginate#405]
im currently using this but why is it showing a large number of pages in the view.

i only want to show about 9 pages at any time with previous and next buttons. currently getting a screen full of pages.

**Comment by MonsieurV** [comment]
Hi,

What props are you using?

-------- Message d'origine --------

**Comment by salivity** [comment]
```
<ReactPaginate 
                breakLabel="..."
                nextLabel=">"
                pageRangeDisplayed={ 2 }
                marginPagesDisplayed={ 2 }
                onPageChange={ handlePageClick }
                pageCount={ 1000 } 
                previousLabel="<"
                initialPage={ 0 }
                forcePage={ 0 }
            />
```

when i click a few pages the entire screen is filled, but when i remove forcePage it works ok.

**Comment by salivity** [comment]
Managed to fix this problem by using parseInt on initialPage, it gets strange behavior on string numerals

**Comment by MonsieurV** [comment]
The v9 will warn when string numerals are provided instead of integers.

https://github.com/AdeleD/react-paginate/blob/v9/react_components/PaginationBoxView.js#L156
