### ISSUE TITLE
pageLabelBuilder does not exists in ReactPaginateProps

### ISSUE THREAD

**Issue by shzawa** [AdeleD/react-paginate#408]
Hi! First of all, thank you for this package!

Attempting to add the pageLabelBuilder attribute to the ReactPaginate component resulted in a TypeScript static analysis error.
I just looked at ReactPaginateProps and the pageLabelBuilder property does not exist in it.
Are there already considerations for such a fix? I couldn't find a related issue.
I'd be willing to contribute for this!

Thanks!

**Comment by MonsieurV** [comment]
Hi @shzawa,

Indeed, that was missing. This should be fixed.

You can test by installing from GitHub:

```sh
npm install github:AdeleD/react-paginate#v8.1.1
```

Thanks for the report

Still to be released on NPM https://github.com/AdeleD/react-paginate/releases/tag/v8.1.1 @AdeleD :)

**Comment by AdeleD** [comment]
Thank you.
v8.1.1 has been released on NPM.
