### ISSUE TITLE
Is the description of v8.1.1 incorrect?

### ISSUE THREAD

**Issue by kuroponzu** [AdeleD/react-paginate#411]
Hello

In the description of tag/v8.1.1, there is an `Add TypeScript definition for pageLabelBuilder prop`.
https://github.com/AdeleD/react-paginate/releases/tag/v8.1.1

However, the only difference with v8.1.0 is that the README has been updated.
https://github.com/AdeleD/react-paginate/compare/v8.1.0...v8.1.1

**Comment by MonsieurV** [comment]
Indeed.

I retagged correctly - however not sure we can reupload to NPM. @AdeleD 
I'll do another minor release for #410.

**Comment by kuroponzu** [comment]
Thank you for releasing [v8.1.2](https://github.com/AdeleD/react-paginate/releases/tag/v8.1.2) 🎉
