### ISSUE TITLE
initial page not getting select

### ISSUE THREAD

**Issue by amirSohel007** [AdeleD/react-paginate#420]
Hello, 

I am using this plugin in my react app. and I am maintaining current page data in redux store, so when user come back on dashboard page I want to render user previous data .... so I store current page count in my store but how I can select that page initally when user come back on dashboard ...

like initally it's selected only page 1 ... but instead of 1 I want to select another page  and that page number will come from my redux store

**Comment by MonsieurV** [comment]
Hi @amirSohel007,

Please tell use which props are you currently using?
Also: can you provide a working example, with a description of intended behavior (that fails)?

Else, please read the doc (`initialPage`, `forcePage`)
