### ISSUE TITLE
After clicking the a tag is highlighted with a color that I can't change

### ISSUE THREAD

**Issue by sinevitch** [AdeleD/react-paginate#422]
I'm styling the a tag

![image](https://user-images.githubusercontent.com/35930695/161997716-d7a57c10-74a2-478a-8776-770d9e2b386c.png)

![image](https://user-images.githubusercontent.com/35930695/161998227-234b1d71-ef56-4ace-b5c8-e5e68446efa9.png)

After clicking on a tag, the color becomes uncontrollable for me for a while

How to fix it? Why use the a tag at all?

**Comment by MonsieurV** [comment]
Hi @sinevitch,

This is a CSS issue, not really related to the lib.

You have CSS rules for `:hover` state, but you should look also for `:visited`, `:active` and `:focus` states.
See https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/
https://developer.mozilla.org/en-US/docs/Web/CSS/:visited
