### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by rpaasche** [AdeleD/react-paginate#423]
It is not possible to use react-paginate with react 18:
![image](https://user-images.githubusercontent.com/33899601/162418750-c9693d49-db8c-46f0-84d3-add44b6c6dcc.png)

**Comment by MonsieurV** [comment]
Hi @rpaasche,

Indeed, the peer dependency declaration for v18 was missing. There shouldn't have any real compatibility issue, so I added it.

https://github.com/AdeleD/react-paginate/commit/f1120b1a92c994ed993bb29fb65d5d0c1363c010

@AdeleD https://github.com/AdeleD/react-paginate/releases/tag/v8.1.3

**Comment by AdeleD** [comment]
v8.1.3 has been released. Thank you.
