### ISSUE TITLE
 'ReactPaginate' cannot be used as a JSX component.  

### ISSUE THREAD

**Issue by shadesOfcodes** [AdeleD/react-paginate#426]
'ReactPaginate' cannot be used as a JSX component.
  Its instance type 'Component<ReactPaginateProps, any, any>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("C:/xxx/xxx/node_modules/@testing-library/react/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
![Uploading Screenshot (166).png…]()

**Comment by shadesOfcodes** [comment]
![Uploading Screenshot (166).png…]()

**Comment by c-jain** [comment]
I also got this error just now. It was not happening before.

**Comment by MonsieurV** [comment]
Do any of the Typescripers know of a fix to apply on https://github.com/AdeleD/react-paginate/blob/master/index.d.ts for this issue?

Does `React.ComponentClass<ReactPaginateProps>` should be changed?

These definitions are maintained by the community.

**Comment by klichg0ky** [comment]
I fixed it temporarily with this.

`import * as React from "react";

import Pagination, { ReactPaginateProps } from "react-paginate";

import { ReactComponent as ArrowLeft } from "@assets/img/svg/icons/arrow_left.svg";
import { ReactComponent as ArrowRight } from "@assets/img/svg/icons/arrow_right_linear.svg";

import styles from "./AppPagination.module.scss";
const ReactPaginate = Pagination as any;
interface Props {}

export const AppPagination: React.FC<Props & ReactPaginateProps> = (props) => {
  return (
    <ReactPaginate`

**Comment by ogheneovo12** [comment]
Thanks, Applying resolution and reinstalling packages fixed it

**Comment by eidriahn** [comment]
> I fixed it temporarily with this code.
> 
> ```
> import * as React from "react";
> 
> import Pagination, { ReactPaginateProps } from "react-paginate";
> 
> import { ReactComponent as ArrowLeft } from "@assets/img/svg/icons/arrow_left.svg";
> import { ReactComponent as ArrowRight } from "@assets/img/svg/icons/arrow_right_linear.svg";
> 
> import styles from "./AppPagination.module.scss";
> const ReactPaginate = Pagination as any;
> interface Props {}
> 
> export const AppPagination: React.FC<Props & ReactPaginateProps> = (props) => {
>   return (
>     <ReactPaginate />
> ```

expanding on the solution suggested above, this is my fix

`const ReactPaginate = Pagination as unknown as FC<ReactPaginateProps>`

this way you don't lose types because of `any`.

I don't like the resolutions fix because you end up having to use react 17...

Ideally the maintainer should support the latest version of the packages.
