### ISSUE TITLE
Help - Pagination buttons not working as intended

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [AdeleD/react-paginate#436]
Hello,
I am trying to include pagination for my application using react-paginate.
I observe the following issues:
1) Page no 1 is always set with blue background
2) Page no 1 is not clickable
3) Previous button is not clickable
4) Clicking on ... dots does not expand the page numbers and does not display the next page
5) Clicking on Next button always loads only the second page.

Please can you help me?

**Comment by RamiroPastor** [comment]
I have these same problems too.

I followed the example on the docs with no changes and I get this stunningly buggy behaviour.

**Comment by ShinValor** [comment]
Same problem here, any update?

**Comment by RamiroPastor** [comment]
> Same problem here, any update?

I'm using [react-js-pagination](https://www.npmjs.com/package/react-js-pagination) now, it alerts of 2 high severity vulnerabilities on installation but works like a charm

**Comment by vijaya-lakshmi-venkatraman** [comment]
Using Pagination from "@material-ui/lab/Pagination". 
Closing the issue
