### ISSUE TITLE
Do not return to page 1 after filtering

### ISSUE THREAD

**Issue by winnie-weinan** [AdeleD/react-paginate#438]
![image](https://user-images.githubusercontent.com/22500544/177481990-2bd83874-1eab-4069-bbf4-d731794f65d6.png)
![image](https://user-images.githubusercontent.com/22500544/177482022-989af54a-6d34-495a-9df2-fb40bb6e1b51.png)

When I re-render after doing some filtering, it doesn't bring the page count back to the first page

**Comment by tareq-rezk** [comment]
@AdeleD  
this issue is exist, 
and sometimes the currentPage state in pagination has a value and doesn't reflect to active class

**Comment by MonsieurV** [comment]
You should use the component in a "controlled" mode, by passing your own `forcePage` for the current page.

This way, you will be able to reset it to the first page when the paginated content change.
