### ISSUE TITLE
Sample code in docs causes multiple re-renders

### ISSUE THREAD

**Issue by sakshambhatt** [AdeleD/react-paginate#441]
The [code in usage section](https://github.com/AdeleD/react-paginate/blob/master/README.md#usage) of the docs causes multiple renders owing to the logic residing in the useEffect hook which has state updates which triggers the re-renders. 
```JSX
 useEffect(() => {
    // Fetch items from another resources.
    const endOffset = itemOffset + itemsPerPage;
    console.log(`Loading items from ${itemOffset} to ${endOffset}`);
    setCurrentItems(items.slice(itemOffset, endOffset));
    setPageCount(Math.ceil(items.length / itemsPerPage));
  }, [itemOffset, itemsPerPage]);
```
After the React 18 update, this has become even more noticeable in the development mode, as React runs every useEffect [twice](https://stackoverflow.com/a/60619061/12967565).
As per the [beta React docs suggestion](https://beta.reactjs.org/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state), we could simply take the logic out of the useEffect and replace the additional states with regular variables, since we already have one useState itemOffset which would cause a re-render and the new values could be calculated every time without the need for an additional render. This, would result in both performance and memory improvements. I have created a [codesandbox](https://codesandbox.io/s/react-paginate-useeffect-02gfrr) of how the changed sample could look and work.
```JSX
const [itemOffset, setItemOffset] = useState(0);
// Fetch items from another resources.
const endOffset = itemOffset + itemsPerPage;
console.log(`Loading items from ${itemOffset} to ${endOffset}`);
const currentItems = items.slice(itemOffset, endOffset);
const pageCount = Math.ceil(items.length / itemsPerPage);
```
An argument could be made that people should spot this and not follow the docs blindly, but even I missed it about six months ago. 
This change in the docs would help beginners by enforcing good patterns and keeping performance high.
Please allow me to take this issue up, and I will submit a PR with updated README file.

**Comment by MonsieurV** [comment]
Fair enough. The example was imagined for the `useEffect` code to be replace by typically API fetching code or similar, but this goes beyond the demonstration of the lib.
