### ISSUE TITLE
Nextjs VM error 

### ISSUE THREAD

**Issue by YoannBuzenet** [AdeleD/react-paginate#443]
Hello,

While running the lib in my nextJS app, I get the error message when I click on the pagination :

`Uncaught TypeError: Cannot read properties of null (reading 'match')     at r (<anonymous>:1:3810)     at e (<anonymous>:1:3870)`

`VM26131:1 `

Did anyone meet this ? Did I do something wrong ?

**Comment by WagdySamih** [comment]
I'm getting same error
did you reach any solution??

**Comment by MonsieurV** [comment]
There is no `match` property on this library.

Isn't the issue with the code loading pages?
