### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by platan** [AdeleD/react-paginate#45]
PaginationBoxView-test.js fails:

```
➜ make test

> react-paginate@0.5.2 test /home/user1/react-paginate
> BABEL_JEST_STAGE=0 jest

Using Jest CLI v0.8.2, jasmine1
 FAIL  __tests__/PaginationBoxView-test.js 
● Runtime Error
SyntaxError: /home/user1/react-paginate/__tests__/PaginationBoxView-test.js: Unexpected token (11:4)
npm ERR! Test failed.  See above for more details.
make: *** [test] Błąd 1
```

My env:
- node - 5.5.0
- npm - 3.3.12

I got the same error while building on travis: https://travis-ci.org/platan/react-paginate/jobs/107331414

**Comment by AdeleD** [comment]
The error comes from babel-jest (see https://github.com/babel/babel-jest/issues/49). I've tried many proposed solutions from this thread but tests are still failing. I'm still looking for a solution. Sorry for the inconvenience.

**Comment by nhz-io** [comment]
will take care of this when i get home from work tonight

**Comment by AdeleD** [comment]
Thank you very much!
