### ISSUE TITLE
itemsPerPage not update on last page.

### ISSUE THREAD

**Issue by ajimsofwan** [AdeleD/react-paginate#453]
when change **itemsPerPage** on last page the **itemsPerPage** not updated.
I have 50 data, **itemsPerPage** is 10 and i have 5 pages. 
When is on page 5, i changed it to 20 for example. the items per page is still on 5.
 But it's ok on page 1-4.

**Comment by MonsieurV** [comment]
Hi @ajimsofwan,

Can we see some of the code?
Are you sure the `pageRangeDisplayed` prop is updated by your code?
