### ISSUE TITLE
How do I make asymetric margin pages

### ISSUE THREAD

**Issue by BurgerBurglar** [AdeleD/react-paginate#465]
I want to make asymetric margin pages, i.e. 
`1 2 3 ... [7] ... 11`
I only see prop `marginPagesDisplayed` that sets both left and right margin pages. How can I achieve this?

**Comment by MonsieurV** [comment]
The simpler would be to use a more modular pagination library or just do your own pagination component.

`react-paginate` is a simple pagination library, to get to the point rapidly. It is not designed for heavy customization.

For eg implementing pagination from scratch using hooks you could read https://dev.to/damiisdandy/pagination-in-javascript-and-react-with-a-custom-usepagination-hook-1mgo as a good start.
