### ISSUE TITLE
pagination align vertically 

### ISSUE THREAD

**Issue by ENGR-MANSOOR** [AdeleD/react-paginate#467]
I have used this module and the default module is vertically aligned and no css changing affecting it, so please can you explain how to make it horizontally or check this issue

**Comment by cmayer153** [comment]
Try giving the ReactPaginate component a classname. Then in your .css file, add 
  display: flex;
  flex-direction: row;

Those attributes are used in the demo js file, and it worked for me when I added them

**Comment by MonsieurV** [comment]
@cmayer153 is right.

Add a className to the component and then CSS accordingly to your needs.

See https://github.com/AdeleD/react-paginate/tree/theme/theme/basic
