### ISSUE TITLE
Buttons not responsive on smaller devices

### ISSUE THREAD

**Issue by newdydx** [AdeleD/react-paginate#471]
All buttons controlling the page should be responsive on all devices

**Comment by newdydx** [comment]
@MonsieurV Can I be assigned to this issue

**Comment by MonsieurV** [comment]
The responsiveness is based on the CSS. This library does not provide (supported) CSS.
So it is up to you to make the CSS responsive.

Unless there is something with the DOM/HTML that is not right?
If so, please be more specific
