### ISSUE TITLE
onClick doc description is wrong

### ISSUE THREAD

**Issue by drdarshanr** [AdeleD/react-paginate#479]
onClick doc description says "**The method to call when an active page is clicked. Exposes the active page object as an argument**.". But this is invoked whenever a page is clicked not just the active page. This is very useful feature and description is misleading. Please correct the description.

I love this project. Keep this project live forever. Thanks a lot brother.

**Comment by wildcatco** [comment]
Are you talking about **onPageActive**?
Description for **onClick** is
**"A callback for any click on the component. Exposes information on the part clicked (for eg. isNext for next control), the next expected page nextSelectedPage & others. Can return false to prevent any page change or a number to override the page to jump to."**
