### ISSUE TITLE
Can't use React <Suspense>?

### ISSUE THREAD

**Issue by theDanielJLewis** [AdeleD/react-paginate#489]
I'm working with hundreds of individual items, being paginated with this component. In the latest React/Next.js, [we have`<Suspense>` to render something until the code and data are loading](https://react.dev/reference/react/Suspense).

But I can't get it to work with react-paginate.

I've tried wrapping `<ReactPaginate>`, `<Items>`,  `<PaginatedItems>` and parent elements. But nothing seems to work. I still get a blank area on page load until the pagination and data finish loading.

Any solutions or workarounds?

**Comment by theDanielJLewis** [comment]
🤦‍♂️ DOH!

I was using very old code for the PaginatedItems function. When I switched to the newer example code, everything now displays so quickly I didn't need Suspense and [Next.js's "loading" file works fine for me now](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming).

**Comment by Rc0fficial** [comment]
Cool..
