### ISSUE TITLE
render issue on next@13.5.4

### ISSUE THREAD

**Issue by Wakype** [AdeleD/react-paginate#506]
Currently, I'm using Next.js version 13.5.4 and employing react-paginate to manage pagination. While react-paginate functions properly in development mode, after building and running the production version, it encounters rendering issues, as depicted in the image below:
![WhatsApp Image 2023-10-28 at 18 38 03 (1)](https://github.com/AdeleD/react-paginate/assets/94674924/7b0c3754-fafe-455b-af61-c2535cbc6010)

After downgrading to version 13.5.3, it is working. I believe there might be an issue with 'react-paginate' in versions 13.5.4 and above. Hence, I resolved it by downgrading the version, and now it works."
![WhatsApp Image 2023-10-28 at 18 38 03](https://github.com/AdeleD/react-paginate/assets/94674924/95531cda-d7fd-469f-bf49-496f4995af36)

**Comment by camcamcamcam** [comment]
Duplicate issue to #501
