### ISSUE TITLE
package.json should better include react-dom as peer dependency

### ISSUE THREAD

**Issue by topgun743** [AdeleD/react-paginate#55]
Hi,
You are using react-dom in your package.json file under dependencies. In my opinion this should be better under peer dependencies. If someone is already using React in his project then it may cause weird conflicting issues.

**Comment by vhpoet** [comment]
fixed in https://github.com/AdeleD/react-paginate/commit/400929a2d0040545394e02441ccca6177b3922c6

**Comment by topgun743** [comment]
Thanks


Get Outlook for Android






On Thu, Mar 24, 2016 at 12:06 PM -0700, "Vahe Hovhannisyan" <notifications@github.com> wrote:












fixed in 400929a
