### ISSUE TITLE
Support React v15

### ISSUE THREAD

**Issue by hkrutzer** [AdeleD/react-paginate#56]
This probably does not require any JS changes. I tested the demo with v15 and it works.
It probably requires https://github.com/AdeleD/react-paginate/issues/55 though.

**Comment by eudisd** [comment]
👍

**Comment by olegafx** [comment]
@AdeleD could you add React v15 support?

**Comment by AdeleD** [comment]
Done in release 1.0.5. Sorry for the delay.
