### ISSUE TITLE
Support a way of setting `href` for the generated links

### ISSUE THREAD

**Issue by sergiu-paraschiv** [AdeleD/react-paginate#57]
I'm using Prerender over my SPA for googlebot and need to set the `href` attributes of the generated links. `rel="next"` and `rel="prev"` would be useful too.

I'm going to fork and make the changes I need but don't have time to submit a proper PR (tests, documentation, go through webpack...) right now.

**Comment by MonsieurV** [comment]
Would be cool to have that!

For those who can't wait, you can use the fork:

```
npm install --save git+https://github.com/MonsieurV/react-paginate.git#12ce1bf9fbb01f78fcbee3680ab116840066f1e7
```

Then add a prop `hrefBuilder`, as a function that return the `href` value following the page number.

Like this:
```
<PaginationBoxView
    ...
    hrefBuilder={(page) => '/page/' + page } />
```

**Comment by MonsieurV** [comment]
Thanks @AdeleD !

(I think we could close the issue :) )

**Comment by sergiu-paraschiv** [comment]
Thanks @MonsieurV, this looks like what I did myself.

**Comment by MonsieurV** [comment]
Too bad I hadn't seen your fork. But yeah, basically I took the work already done by @steppefox, added some doc, _et voilà !_

**Comment by sergiu-paraschiv** [comment]
This was my commit: https://github.com/sergiu-paraschiv/react-paginate/commit/74f0be4dbddc702b6c5a437bd52aa9b95b5b9483

Didn't want to pull-request it because I edited the transpiled sources directly.
