### ISSUE TITLE
Break page className support

### ISSUE THREAD

**Issue by stepankuzmin** [AdeleD/react-paginate#72]
Hi there! I think, that it would be more consistent to support label for ellipsis className instead of hardcoding `break` as className.

**Comment by rcsole** [comment]
Any news on this?

**Comment by slackday** [comment]
+1 

This turned out to be the most difficult part for me as well while styling this component. Otherwise react-paginate works really great and is so easy to implement! Great job!

**Comment by AdeleD** [comment]
Thank you very much for your support. 
I just merged the PR so, the `breakClassName` prop is available in version 2.1.3.
