### ISSUE TITLE
react-dom version bump

### ISSUE THREAD

**Issue by adack123** [AdeleD/react-paginate#75]
![image](https://cloud.githubusercontent.com/assets/8890348/14790298/44664aa6-0ad6-11e6-9fb4-6b7921f6795a.png)

Do you all have plans to bump the react-dom version?

**Comment by gabriel-naressi** [comment]
:+1:

**Comment by AdeleD** [comment]
Done

**Comment by leandrooriente** [comment]
Please rollback to React 15.0.0. It's common to use the max React version to 15.0.0. This package area breaking a lot of compatibility :(

**Comment by AdeleD** [comment]
Sorry about that, I forgot to bump up the version to 2.0. Version 1.0.5 of react-paginate is now marked as deprecated, with a message explaining which versions of react-paginate to use with react < 0.14 and with react > 15.0. I hope this will help people to understand what's going on.

In your case, I think you can use react-paginate 2.0.0 now.
