### ISSUE TITLE
Danger: Discarding unexpected node

### ISSUE THREAD

**Issue by amit1911** [AdeleD/react-paginate#78]
The pagination component is not working properly for me. I keep getting the following error

```
Danger: Discarding unexpected node <li class="disabled"></li>
```

i am using react 0.14.8, react-dom 0.14.8 and react-paginate 0.5.7

**Comment by lxkuz** [comment]
@amit1911  I had same issue when I by error used <li> inside  breakLabel option.

**Comment by amit1911** [comment]
i have switched to the pagination component in react-bootstrap.
