### ISSUE TITLE
Broken React 0.14 support

### ISSUE THREAD

**Issue by olegafx** [AdeleD/react-paginate#79]
Today I found that new version of react-paginate stopped working. Looks like you forgot to bump up repo version to 2.0. (changing React version [could broke](http://semver.org/) someones project).

**Comment by EwanValentine** [comment]
+1

**Comment by AdeleD** [comment]
You're right. Very sorry about that :( I haven't changed the code when I've upgraded, and I forgot to bump up the version to 2.0... I think I can't rollback now, it would be worse...

**Comment by AdeleD** [comment]
Version 1.0.5 is now marked as deprecated, with a message explaining which versions of react-paginate to use with react < 0.14 and with react > 15.0. I hope this will help people to understand what's going on.

**Comment by olegafx** [comment]
Nice. Thank you, @AdeleD
