### ISSUE TITLE
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null

### ISSUE THREAD

**Issue by shaimo** [AdeleD/react-paginate#8]
This worked for me before, so maybe it's a compatibility issue with react 0.13?
I simply require('react-paginate'), then try to render ReactPaginate:
```
    React.render(<ReactPaginate />, document.getElementById(options.element_id))
```
and I get the error:
```
Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null ReactClass.js:842 ReactClass.createClass.Constructor ReactLegacyElement.js:191 ReactLegacyElementFactory.wrapCreateElement.legacyCreateElement PaginationBoxView.jsx:84 React.createClass.render ReactCompositeComponent.js:1260 
(anonymous function) ReactPerf.js:50 
ReactPerf.measure.wrapper ReactCompositeComponent.js:802 
(anonymous function) ReactPerf.js:50 
ReactPerf.measure.wrapper ReactComponent.js:405 ReactComponent.Mixin._mountComponentIntoNode Transaction.js:134
 Mixin.perform ReactComponent.js:381 
ReactComponent.Mixin.mountComponentIntoNode ReactMount.js:312 
(anonymous function) ReactPerf.js:50 
ReactPerf.measure.wrapper ReactMount.js:381 
ReactMount.render ReactPerf.js:50 
ReactPerf.measure.wrapper TabContent.js.jsx:92 
category_show
```
category_show is the first function called and is just doing the render...

**Comment by shaimo** [comment]
Forgot to mention that there is also a warning in the console:
Warning: This JSX uses a plain function. Only React components are valid in React's JSX transform. 
warning.js:36
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory warning.js:48

**Comment by shaimo** [comment]
After a lot of further investigation, this seems to be a general issue when using react/addons - https://github.com/facebook/react/issues/3593
The issue goes away when using just 'react'. Unfortunately this module currently uses the addons so need to wait for React to fix their issue...

**Comment by AdeleD** [comment]
Thank you very much for your investigation.
Indeed react/addons is not really needed in PaginationListView.jsx. I used it for 'classSet' but it is not needed anymore as I now import the 'classname' package.

**Comment by AdeleD** [comment]
I close the issue. Answers are available here: https://github.com/facebook/react/issues/3593. Thank you.
