### ISSUE TITLE
Error in PaginationBoxView

### ISSUE THREAD

**Issue by amitkumarsingh** [AdeleD/react-paginate#84]
Getting the below issue on installing and using it.

ERROR in ./~/react-paginate/dist/PaginationBoxView.js
Module not found: Error: Cannot resolve module 'react-addons-create-fragment' in 
/home/superprofs/cms/node_modules/react-paginate/dist
 @ ./~/react-paginate/dist/PaginationBoxView.js 17:33-72

**Comment by jfeltesse-mdsol** [comment]
you need to manually install the peer dependency, as npm should have told you:

```
├── UNMET PEER DEPENDENCY react-addons-create-fragment@^15.0.0
└─┬ react-paginate@2.0.1
  └── classnames@1.2.2

npm WARN react-paginate@2.0.1 requires a peer of react-addons-create-fragment@^15.0.0 but none was installed.
```
