### ISSUE TITLE
Precompiled release

### ISSUE THREAD

**Issue by KaiStapel** [AdeleD/react-paginate#85]
Hi,

is it possible to provide a pre-compiled release of react-paginate that only requires react.js and react-dom.js to be included? This could ease, for example, some easy tutorials without having to install npm.

Thanks and best regards

Kai

**Comment by nicoladj77** [comment]
@KaiStapel how did you end up doing this?Just cloning and building?

**Comment by KaiStapel** [comment]
Yes, I believe so. I somehow created the build and statically included it in my project.

**Comment by MonsieurV** [comment]
There is a Babelified version in `dist`.

Is this good?

If yes you can close :)
