### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by cAstraea** [AdeleD/react-paginate#87]
Hello, 
I'm getting an unexpected token on handlePageClick = function handlePageClick(data)  , what does this mean , surely I missed something. 
Trying to run it in a symfony app via https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js

**Comment by cAstraea** [comment]
Got it  working

**Comment by finkbg** [comment]
So how did you get it working?
