### ISSUE TITLE
Pagination not navigable with keyboard

### ISSUE THREAD

**Issue by adransom** [AdeleD/react-paginate#89]
Due to the use of `<a>` tags without `href` or `tabindex`, the page elements are not navigable by keyboard, which is a rather big accessibility issue.

If you are interested in fixing this, I can maybe attempt a pull request, either using `tabindex=0`, switching to `button`s or adding an empty `href` attribute. Do you have any preference?

**Comment by AdeleD** [comment]
Yes, I'm interested in fixing this. 
I prefer an implementation with `tabindex` because several people had problems with empty hrefs causing page reloads. That's why hrefs were removed here: https://github.com/AdeleD/react-paginate/pull/65
Thank you.

**Comment by coljung** [comment]
@adransom Will you work on this implementation ?

**Comment by adransom** [comment]
@coljung Unfortunately I'm not able to work on this at the moment, sorry :(

**Comment by hozefaj** [comment]
@AdeleD I will work to fix this if not fixed yet.
