### ISSUE TITLE
Force new current page as property

### ISSUE THREAD

**Issue by ragingsquirrel3** [AdeleD/react-paginate#9]
I understand that when the component mounts, I can pass initialPage as a property.  After that, the current page is determined by internal state.  For me, the problem is that I want to reset the current page from the parent (as a property).

My use case is paginated search results, and I want to always be on the first page after a new search.  Right now, it seems I can only do this by unmounting the paginate component, and passing a new initialPage.

The solution, for me, would be to have an optional currentPage property, which, if absent, would defer to existing behavior.

**Comment by AdeleD** [comment]
I understand. Thank you for your PR ;)

**Comment by cAstraea** [comment]
Hello Travis , sorry to bother you.
 Did you find a solution for this? Could you confirm if we're having the same problem http://recordit.co/TU5Wy2OI5W ? 

I'm trying out your solution with ReactDOM.unmountComponentAtNode(document.getElementById('react-paginate'));
but need to make some changes to the search component to move it outside the paginate component first.

**Comment by sami616** [comment]
This approach seemed to work for me when needing to update the selected page based on a prop condition 

```
  let forcePageObj = {}
  if (props.page === 0) {
    forcePageObj['forcePage'] = 0
  }

  return (
      <ReactPaginate
        onPageChange={handlePageChange}
        pageRangeDisplayed={3}
        marginPagesDisplayed={1}
        {...forcePageObj}
        pageCount={props.nbPages}
      />
  )
````

**Comment by yogitaba-gohil** [comment]
works for me
