### ISSUE TITLE
clickCallback gets called without a click

### ISSUE THREAD

**Issue by hackingbeauty** [AdeleD/react-paginate#91]
Hello,

I noticed that when react-paginate first gets displayed on a page, it automatically calls the clickCallback handler.

I don't want it to do this.  I just want the clickCallback handler called when a page number is clicked.

Am I doing something wrong?

**Comment by AdeleD** [comment]
Hello @hackingbeauty,

Indeed, when react-paginate first gets displayed on a page, it automatically calls the clickCallback handler. That's because the clickCallback function is supposed to be the place where you load the content you want to display on a particular page.

As you can initialize the component to display the page of your choice (page 6 for example), it will call the clickCallback at first in order to load the content of page 6.

I hope this helps.

**Comment by jzlxiaohei** [comment]
the first data has been fetched, then the `callback` will fetch duplicated data again.

i don't think automatically calls the clickCallback  is good.

**Comment by donperi** [comment]
Having issues because of this too.
Data is loaded from other method.
onClick handles a pushState to a new url with the new page number.

Being called on mount causes me a loop.

**Comment by donperi** [comment]
A solution could be to add another props like `onLoad/onMount` if is needed to call the handler when component is loaded.

**Comment by coljung** [comment]
Might this be causing an issue where my initial page is linked to [2], where as [1] links to a non existent page-0 ?  I created this ticket btw: #104

**Comment by coljung** [comment]
One thing i just noticed is that the demo provided on this repo doesn't call the 'clickCallback' on load.

**Comment by terencechow** [comment]
Looks like if you use `initialSelected` it will invoke the click callback on load but if you use `forceSelected` it will not.

**Comment by cheersjosh** [comment]
@terencechow spot on, seems to be working on my end using `forceSelected`.

**Comment by AdeleD** [comment]
For your information, since react-paginate 3.0.0, the `clickCallback` (=`onPageLoad`) isn't called anymore during initialization.

**Comment by mskec** [comment]
@AdeleD I can see [here](https://github.com/AdeleD/react-paginate/blob/master/react_components/PaginationBoxView.js#L60) that it is still called. 
Would you be open to PR where I add bool flag whether to call it or not on initial render?

**Comment by AdeleD** [comment]
Yes the callback is still called because: https://github.com/AdeleD/react-paginate/issues/116
If you don't want the callback being called during initialization, don't pass prop `initialPage` when you initialize the component.
```javascript
<ReactPaginate previousLabel={"previous"}
                       nextLabel={"next"}
                       initialPage={1} // Remove this line
                       pageCount={this.state.pageCount}
                       onPageChange={this.handlePageClick} />
```
Is it OK for you this way?

**Comment by mskec** [comment]
By removing that line, callback will not be called. This works if you always have `initialPage={1}`, but won't work if you need to change initial page.

**Comment by AdeleD** [comment]
Yes indeed. So, you're right, adding a boolean flag to change this behaviour if needed may be a good idea.
